#!/usr/bin/python
# readingbigcorpus.py
# based on https://www.ibm.com/developerworks/xml/library/x-hiperfparse/

from lxml import etree
import json 
import collections
import sys, getopt

#results = etree.parse(infile, parser)    
 
# When iterated over, 'results' will contain the output from 
# target parser's close() method
 
#out = open('titles.txt', 'w')
#out.write('\n'.join(results))
#out.close()

univ_pos_name_variants = {
    "t-dp-afa-": "x",  # added to match morpheus. Review required.
    "t-dp-afn-": "x",
    "t-dp-afv-": "x",
    "t-pp-afa-": "x",
    "t-pp-afg-": "x",
    "t-pp-afn-": "x",
    "t-pp-afv-": "x",
    "t-pp-amd-": "x",
    "t-pp-and-": "x",
    "t-sa-pmn-": "x",
    "t-sa-pmv-": "x",
    "t-sp-afa-": "x",
    "t-sp-afd-": "x",
    "t-sp-afg-": "x",
    "t-sp-afn-": "x",
    "t-sp-afv-": "x",
    "t-sp-amn-": "x",
    "t-sp-amv-": "x",
    "t-sp-ana-": "x",
    "t-sp-ann-": "x", 
    "t-sp-anv-": "x",  # added to match morpheus. Review required. 
    "v2dpsa---": "x",
    "t-sa-ana-": "x",
    "t-sa-ann-": "x",
    "t-sa-anv-": "x",
    "n--------": "x",
    "a-d---fv-": "x",
    "a-d---nv-": "x",
    "a-p---ngc": "x",
    "n-d---fv-": "x",
    "a-d---fas": "x",
    "a-d---fns": "x",
    "a-d---fvs": "x",
    "a-p---nvs": "x",
    "a-s---fvs": "x",
    "a-s---nvc": "x",
    "a-d---fac": "x",
    "a-d---fnc": "x",
    "a-d---fvc": "x",
    "a-p---nvc": "x",
    "a-s---fvc": "x",
    "t-pp-ama-": "x",
    "t-sf-amn-": "x",
    "t-sf-amv-": "x",
    "t-sf-ana-": "x",
    "t-sf-ann-": "x",
    "t-sf-anv-": "x",
    "t-pp-amn-": "x",
    "t-pp-amv-": "x",
    "a-d---nd-": "x",
    "t-pp-emn-": "x",
    "t-pp-emv-": "x",
    "t-sp-efn-": "x",
    "t-sp-efv-": "x",
    "t-sp-emg-": "x",
    "t-sp-emn-": "x",
    "t-sp-eng-": "x",
    "t-pf-mmn-": "x",
    "t-pf-mmv-": "x",
    "v2plie---": "x",
    "v2ppse---": "x",
    "v2prme---": "x",
    "t-dp-efa-": "x",
    "t-dp-efn-": "x",
    "t-dp-efv-": "x",
    "t-pp-efn-": "x",
    "t-pp-efv-": "x",
    "t-pp-ema-": "x",
    "t-pp-ena-": "x",
    "t-pp-enn-": "x",
    "t-pp-env-": "x",
    "t-sp-efa-": "x",
    "t-sp-efd-": "x",
    "t-sp-emd-": "x",
    "t-sp-end-": "x",
    "n-d---nv-": "x",
    "t-da-mma-": "x",
    "t-da-mmn-": "x",
    "t-da-mmv-": "x",
    "t-da-mna-": "x",
    "t-da-mnn-": "x",
    "t-da-mnv-": "x",
    "t-da-pma-": "x",
    "t-da-pmn-": "x",
    "t-da-pmv-": "x",
    "t-da-pna-": "x",
    "t-da-pnn-": "x",
    "t-da-pnv-": "x",
    "t-pa-mmn-": "x",
    "t-pa-mmv-": "x",
    "t-pa-pma-": "x",
    "t-pa-pmn-": "x",
    "t-pa-pmv-": "x",
    "t-pa-pna-": "x",
    "t-pa-pnn-": "x",
    "t-pa-pnv-": "x",
    "t-pp-efg-": "x",
    "t-pp-emg-": "x",
    "t-pp-eng-": "x",
    "t-sa-mfn-": "x",
    "t-sa-mfv-": "x",
    "t-sa-mma-": "x",
    "t-sa-mmg-": "x",
    "t-sa-mmn-": "x",
    "t-sa-mna-": "x",
    "t-sa-mng-": "x",
    "t-sa-mnn-": "x",
    "t-sa-mnv-": "x",
    "t-sa-pma-": "x",
    "t-sa-pmd-": "x",
    "t-sa-pna-": "x",
    "t-sa-pnd-": "x",
    "t-sa-pnn-": "x",
    "t-sa-pnv-": "x",
    "t-sp-ema-": "x",
    "t-sp-ena-": "x",
    "t-sp-enn-": "x",
    "t-sp-env-": "x",
    "t-da-afa-": "x",
    "t-da-afn-": "x",
    "t-da-afv-": "x",
    "t-dp-ama-": "x",
    "t-dp-amn-": "x",
    "t-dp-amv-": "x",
    "t-dp-ana-": "x",
    "t-dp-ann-": "x",
    "t-dp-anv-": "x",
    "t-pa-ama-": "x",
    "t-pa-amg-": "x",
    "t-pa-amn-": "x",
    "t-pa-amv-": "x",
    "t-pa-ana-": "x",
    "t-pa-ang-": "x",
    "t-pa-ann-": "x",
    "t-pa-anv-": "x",
    "t-pf-ama-": "x",
    "t-pp-amg-": "x",
    "t-pp-ana-": "x",
    "t-pp-ang-": "x",
    "t-pp-ann-": "x",
    "t-pp-anv-": "x",
    "t-pr-ama-": "x",
    "t-sa-afn-": "x",
    "t-sa-afv-": "x",
    "t-sa-ama-": "x",
    "t-sa-amd-": "x",
    "t-sa-amg-": "x",
    "t-sa-amn-": "x",
    "t-sa-amv-": "x",
    "t-sa-and-": "x",
    "t-sa-ang-": "x",
    "t-sp-ama-": "x",
    "t-sp-amg-": "x",
    "t-sp-ang-": "x",
    "v-ptiama-": "x",
    "v2ptia---": "x",
    "v3pama---": "x",
    "v3stia---": "x",
    "t-df-afa-": "x",
    "t-df-afn-": "x",
    "t-df-afv-": "x",
    "t-df-mfa-": "x",
    "t-df-mfn-": "x",
    "t-df-mfv-": "x",
    "t-pf-afg-": "x",
    "t-pf-afn-": "x",
    "t-pf-afv-": "x",
    "t-pf-amd-": "x",
    "t-pf-amg-": "x",
    "t-pf-amn-": "x",
    "t-pf-amv-": "x",
    "t-pf-ana-": "x",
    "t-pf-and-": "x",
    "t-pf-ang-": "x",
    "t-pf-ann-": "x",
    "t-pf-anv-": "x",
    "t-pf-mfd-": "x",
    "t-pf-mfg-": "x",
    "t-pf-mfn-": "x",
    "t-pf-mfv-": "x",
    "t-pf-mma-": "x",
    "t-pf-mmg-": "x",
    "t-pf-mna-": "x",
    "t-pf-mng-": "x",
    "t-pf-mnn-": "x",
    "t-pf-mnv-": "x",
    "t-sf-afa-": "x",
    "t-sf-afd-": "x",
    "t-sf-afn-": "x",
    "t-sf-afv-": "x",
    "t-sf-ama-": "x",
    "t-sf-amd-": "x",
    "t-sf-and-": "x",
    "t-sf-mfa-": "x",
    "t-sf-mfd-": "x",
    "t-sf-mfg-": "x",
    "t-sf-mfn-": "x",
    "t-sf-mfv-": "x",
    "t-sf-mma-": "x",
    "t-sf-mmd-": "x",
    "t-sf-mmn-": "x",
    "t-sf-mna-": "x",
    "t-sf-mnd-": "x",
    "t-sf-mnn-": "x",
    "t-sf-mnv-": "x",
    "t-sp-amd-": "x",
    "t-sp-and-": "x",
    "v1pfoa---": "x",
    "v1sfoa---": "x",
    "v3pfoa---": "x",
    "t-pp-efd-": "x",
    "t-pr-amd-": "x",
    "t-pr-amg-": "x",
    "t-pr-amn-": "x",
    "t-pr-amv-": "x",
    "t-pr-and-": "x",
    "t-pr-ang-": "x",
    "t-pr-emd-": "x",
    "t-pr-emn-": "x",
    "t-pr-emv-": "x",
    "t-pr-end-": "x",
    "t-sp-efg-": "x",
    "t-sr-amn-": "x",
    "t-sr-amv-": "x",
    "t-sr-efa-": "x",
    "t-sr-efn-": "x",
    "t-sr-efv-": "x",
    "t-sr-ema-": "x",
    "t-sr-emd-": "x",
    "t-sr-ena-": "x",
    "t-sr-end-": "x",
    "t-sr-enn-": "x",
    "t-sr-env-": "x",
    "v-ptiamd-": "x",
    "v-ptiand-": "x",
    "v-stiamn-": "x",
    "v1ptia---": "x",
    "v1stia---": "x",
    "v2stia---": "x",
    "v2stim---": "x",
    "v3ptia---": "x",
    "t-da-ama-": "x",
    "t-da-amn-": "x",
    "t-da-amv-": "x",
    "t-da-ana-": "x",
    "t-da-ann-": "x",
    "t-da-anv-": "x",
    "t-da-mfa-": "x",
    "t-da-mfn-": "x",
    "t-da-mfv-": "x",
    "t-da-pfa-": "x",
    "t-da-pfn-": "x",
    "t-da-pfv-": "x",
    "t-dr-efa-": "x",
    "t-dr-efn-": "x",
    "t-dr-efv-": "x",
    "t-pa-afn-": "x",
    "t-pa-afv-": "x",
    "t-pa-amd-": "x",
    "t-pa-and-": "x",
    "t-pa-mfg-": "x",
    "t-pa-mmd-": "x",
    "t-pa-mmg-": "x",
    "t-pa-mna-": "x",
    "t-pa-mnd-": "x",
    "t-pa-mng-": "x",
    "t-pa-mnn-": "x",
    "t-pa-mnv-": "x",
    "t-pp-emd-": "x",
    "t-pp-end-": "x",
    "t-pr-efg-": "x",
    "t-pr-emg-": "x",
    "t-pr-ena-": "x",
    "t-pr-eng-": "x",
    "t-pr-enn-": "x",
    "t-pr-env-": "x",
    "t-sa-afd-": "x",
    "t-sa-pfg-": "x",
    "t-sa-pfn-": "x",
    "t-sa-pfv-": "x",
    "t-sa-pmg-": "x",
    "t-sa-png-": "x",
    "t-sr-emn-": "x",
    "v2sfoa---": "x",
    "t-pa-mfd-": "x",
    "t-pa-mfn-": "x",
    "t-pa-mfv-": "x",
    "t-sa-mfd-": "x",
    "t-sa-mfg-": "x",
    "t-sr-efg-": "x",
    "a-p---fvs": "x",
    "t-pa-pmg-": "x",
    "t-pa-png-": "x",
    "a-p---fgs": "x",
    "t-dr-pfa-": "x",
    "t-dr-pfn-": "x",
    "t-dr-pfv-": "x",
    "t-pr-pma-": "x",
    "t-pr-pna-": "x",
    "t-pr-pnn-": "x",
    "t-pr-pnv-": "x",
    "t-sr-pfn-": "x",
    "t-sr-pfv-": "x",
    "t-sr-pmn-": "x",
    "v1spip---": "x",
    "v2spmp---": "x",
    "t-pr-ema-": "x",
    "t-sr-ana-": "x",
    "t-sr-ann-": "x",
    "t-sr-anv-": "x",
    "t-pa-pmd-": "x",
    "t-pa-pnd-": "x",
    "t-pf-pfg-": "x",
    "t-pf-pmg-": "x",
    "t-pf-png-": "x",
    "t-sa-pfd-": "x",
    "t-pp-afd-": "x",
    "t-pp-efa-": "x",
    "v--tne---": "x",
    "a-p---fvc": "x",
    "a-s---fdc": "x",
    "t-df-ama-": "x",
    "t-df-amn-": "x",
    "t-df-amv-": "x",
    "t-df-ana-": "x",
    "t-df-ann-": "x",
    "t-df-anv-": "x",
    "v2daip---": "x",
    "v2dasp---": "x",
    "v2pamp---": "x",
    "v3dasp---": "x",
    "v3pfom---": "x",
    "a-d----a-": "x",
    "a-d----n-": "x",
    "a-d----v-": "x",
    "a-d---mas": "x",
    "a-d---mns": "x",
    "a-d---mvs": "x",
    "a-d---nas": "x",
    "a-d---nns": "x",
    "a-d---nvs": "x",
    "a-p----d-": "x",
    "a-s---ngs": "x",
    "t-pa-pfg-": "x",
    "t-pf-afa-": "x",
    "t-sa-pfa-": "x",
    "t-sf-afg-": "x",
    "v--pnm---": "x",
    "v--rnm---": "x",
    "v1spim---": "x",
    "v2piim---": "x",
    "v2ppim---": "x",
    "v2ppmm---": "x",
    "v2siim---": "x",
    "v2spim---": "x",
    "v2spmm---": "x",
    "v2spsm---": "x",
    "v3diim---": "x",
    "v3piim---": "x",
    "v3siim---": "x",
    "v3spim---": "x",
    "v3spom---": "x",
    "v3spsm---": "x",
    "v3srim---": "x",
    "v-stiamv-": "x",
    "v-stiana-": "x",
    "v-stiann-": "x",
    "v-stianv-": "x",
    "a-p---mvc": "x",
    "r-------c": "x",
    "t-pa-efg-": "x",
    "t-pa-ema-": "x",
    "t-pa-emd-": "x",
    "t-pa-emg-": "x",
    "t-pa-emn-": "x",
    "t-pa-emv-": "x",
    "t-pa-end-": "x",
    "t-pa-eng-": "x",
    "t-pf-ema-": "x",
    "t-pf-emn-": "x",
    "t-pf-emv-": "x",
    "t-pr-efn-": "x",
    "t-pr-efv-": "x",
    "t-sa-efa-": "x",
    "t-sa-efg-": "x",
    "t-sa-ema-": "x",
    "t-sa-emd-": "x",
    "t-sa-emg-": "x",
    "t-sa-emn-": "x",
    "t-sa-ena-": "x",
    "t-sa-end-": "x",
    "t-sa-eng-": "x",
    "t-sa-enn-": "x",
    "t-sa-env-": "x",
    "t-sf-ema-": "x",
    "t-sf-emg-": "x",
    "t-sf-emn-": "x",
    "t-sf-ena-": "x",
    "t-sf-eng-": "x",
    "t-sf-enn-": "x",
    "t-sf-env-": "x",
    "t-sr-efd-": "x",
    "v1paie---": "x",
    "v1pfie---": "x",
    "v2paie---": "x",
    "t-dp-ema-": "x",
    "t-dp-emn-": "x",
    "t-dp-emv-": "x",
    "t-dp-ena-": "x",
    "t-dp-enn-": "x",
    "t-dp-env-": "x",
    "t-pa-afg-": "x",
    "t-pa-pfa-": "x",
    "t-pa-pfn-": "x",
    "t-pa-pfv-": "x",
    "t-sa-afa-": "x",
    "t-sa-afg-": "x",
    "t-sa-mmd-": "x",
    "t-sa-mnd-": "x",
    "v2pfip---": "x",
    "v3dase---": "x",
    "v3prme---": "x",
    "v3srme---": "x",
    "n-d----n-": "x",
    "n-d----v-": "x",
    "n-p----a-": "x",
    "n-p----n-": "x",
    "n-p----v-": "x",
    "n-s----a-": "x",
    "t-dr-afa-": "x",
    "t-dr-afn-": "x",
    "t-dr-afv-": "x",
    "t-dr-ama-": "x",
    "t-dr-amn-": "x",
    "t-dr-amv-": "x",
    "t-dr-ana-": "x",
    "t-dr-ann-": "x",
    "t-dr-anv-": "x",
    "t-pf-mmd-": "x",
    "t-pf-mnd-": "x",
    "t-pr-afg-": "x",
    "t-pr-ana-": "x",
    "t-pr-ann-": "x",
    "t-pr-anv-": "x",
    "t-pr-efd-": "x",
    "t-pt-emd-": "x",
    "t-pt-end-": "x",
    "t-sp-pmn-": "x",
    "t-sr-afa-": "x",
    "t-sr-afn-": "x",
    "t-sr-afv-": "x",
    "t-sr-ama-": "x",
    "t-sr-amd-": "x",
    "t-sr-amg-": "x",
    "t-sr-and-": "x",
    "t-sr-ang-": "x",
    "t-sr-emg-": "x",
    "t-sr-eng-": "x",
    "t-st-ema-": "x",
    "t-st-ena-": "x",
    "t-st-enn-": "x",
    "t-st-env-": "x",
    "v-ptiafg-": "x",
    "v-ptiamg-": "x",
    "v-ptiamn-": "x",
    "v-ptiamv-": "x",
    "v-ptiang-": "x",
    "v-stiafa-": "x",
    "v3ptie---": "x",
    "a-s---ngc": "x",
    "t-sp-mma-": "x",
    "t-sp-mna-": "x",
    "t-sp-mnn-": "x",
    "t-sp-mnv-": "x",
    "t-sr-mma-": "x",
    "t-sr-mna-": "x",
    "t-sr-mnn-": "x",
    "t-sr-mnv-": "x",
    "t-pa-afa-": "x",
    "t-pa-mma-": "x",
    "v1sfom---": "x",
    "v2pfom---": "x",
    "v2sfom---": "x",
    "v3sfom---": "x",
    "t-pr-efa-": "x",
    "v3pfip---": "x",
    "t-sf-amg-": "x",
    "t-sf-ang-": "x",
    "e--------": "x",
    "t-sa-mfa-": "x",
    "v3dasa---": "x",
    "t-dr-ema-": "x",
    "t-dr-emn-": "x",
    "t-dr-emv-": "x",
    "t-dr-ena-": "x",
    "t-dr-enn-": "x",
    "t-dr-env-": "x",
    "v2dpoa---": "x",
    "t-pa-ena-": "x",
    "t-pa-enn-": "x",
    "t-pa-env-": "x",
    "t-pp-mfn-": "x",
    "t-pp-mfv-": "x",
    "t-pp-mma-": "x",
    "t-pp-mmn-": "x",
    "t-pp-mmv-": "x",
    "t-sp-mfa-": "x",
    "t-sp-mfd-": "x",
    "t-sp-mfn-": "x",
    "t-sp-mfv-": "x",
    "t-sp-mmd-": "x",
    "t-sp-mmn-": "x",
    "t-sp-mnd-": "x",
    "v1piim---": "x",
    "v1ppim---": "x",
    "v1siim---": "x",
    "t-pa-pfd-": "x",
    "v2pfoa---": "x",
    "v3damm---": "x",
    "t-sf-pma-": "x",
    "t-sf-pna-": "x",
    "t-sf-pnn-": "x",
    "t-sf-pnv-": "x",
    "t-dp-mfa-": "x",
    "t-dp-mfn-": "x",
    "t-dp-mfv-": "x",
    "t-pp-mfg-": "x",
    "t-pp-mmd-": "x",
    "t-pp-mmg-": "x",
    "t-pp-mna-": "x",
    "t-pp-mnd-": "x",
    "t-pp-mng-": "x",
    "t-pp-mnn-": "x",
    "t-pp-mnv-": "x",
    "t-pr-mfg-": "x",
    "t-pr-mma-": "x",
    "t-pr-mmd-": "x",
    "t-pr-mmg-": "x",
    "t-pr-mmn-": "x",
    "t-pr-mmv-": "x",
    "t-pr-mnd-": "x",
    "t-pr-mng-": "x",
    "t-sp-mmg-": "x",
    "t-sp-mng-": "x",
    "t-sr-mmg-": "x",
    "t-sr-mmn-": "x",
    "t-sr-mng-": "x",
    "v1plim---": "x",
    "v1ppom---": "x",
    "v1ppsm---": "x",
    "v1prim---": "x",
    "v1spsm---": "x",
    "v1srim---": "x",
    "v2plim---": "x",
    "v2ppsm---": "x",
    "v2prim---": "x",
    "v2prmm---": "x",
    "v2spom---": "x",
    "v2srim---": "x",
    "v3ppim---": "x",
    "v3ppom---": "x",
    "v3ppsm---": "x",
    "v3prim---": "x",
    "a-p----gc": "x",
    "a-d---mac": "x",
    "a-d---mvc": "x",
    "a-d---nac": "x",
    "a-d---nnc": "x",
    "a-d---nvc": "x",
    "t-pp-pmn-": "x",
    "t-pp-pmv-": "x",
    "v2plip---": "x",
    "v2prip---": "x",
    "t-sa-efn-": "x",
    "t-sa-efv-": "x",
    "t-sa-emv-": "x",
    "v1paoe---": "x",
    "v3same---": "x",
    "t-sf-mmg-": "x",
    "t-sf-mng-": "x",
    "v-stiamg-": "x",
    "v-stiang-": "x",
    "v3stoa---": "x",
    "v2diim---": "x",
    "v2dpim---": "x",
    "v2dpmm---": "x",
    "v3dpim---": "x",
    "t-sf-pmg-": "x",
    "t-sf-png-": "x",
    "v2pfie---": "x",
    "a-------c": "x",
    "t-st-emg-": "x",
    "t-st-emn-": "x",
    "t-st-eng-": "x",
    "t-pf-mfa-": "x",
    "v1spom---": "x",
    "v2srmm---": "x",
    "t-sr-mfn-": "x",
    "t-sr-mfv-": "x",
    "t-sp-mfg-": "x",
    "v3spmm---": "x",
    "v3dpoa---": "x",
    "t-pa-afd-": "x",
    "t-pr-afa-": "x",
    "t-pr-afd-": "x",
    "t-pr-afn-": "x",
    "t-pr-afv-": "x",
    "t-sr-afd-": "x",
    "t-sr-afg-": "x",
    "n-----nv-": "x",
    "v1pfip---": "x",
    "a-d----d-": "x",
    "a-d----g-": "x",
    "v2dtia---": "x",
    "v3dtia---": "x",
    "t-sr-emv-": "x",
    "v-ptiana-": "x",
    "v-ptiann-": "x",
    "v-ptianv-": "x",
    "v-stiama-": "x",
    "v2dpie---": "x",
    "a-d----ac": "x",
    "a-d----nc": "x",
    "a-d----vc": "x",
    "t-sp-emv-": "x",
    "v--tnm---": "x",
    "v2ptim---": "x",
    "v2dfie---": "x",
    "v2dtie---": "x",
    "v3dfie---": "x",
    "v3dtie---": "x",
    "a-p----g-": "x",
    "v3dama---": "x",
    "t-pf-pmn-": "x",
    "t-pf-pmv-": "x",
    "t-sf-pmd-": "x",
    "t-sf-pnd-": "x",
    "t-da-pmd-": "x",
    "t-da-pmg-": "x",
    "t-da-pnd-": "x",
    "t-da-png-": "x",
    "t-pf-pfa-": "x",
    "t-pt-efn-": "x",
    "t-pt-efv-": "x",
    "t-pt-ema-": "x",
    "t-sf-pfg-": "x",
    "t-st-efd-": "x",
    "t-pf-efn-": "x",
    "t-pf-efv-": "x",
    "t-sf-efd-": "x",
    "v2paoe---": "x",
    "t-pt-emn-": "x",
    "t-pt-emv-": "x",
    "t-pa-mfa-": "x",
    "t-pf-pma-": "x",
    "t-sf-pmn-": "x",
    "t-pf-afd-": "x",
    "v3pamp---": "x",
    "t-sp-pmd-": "x",
    "t-sp-pnd-": "x",
    "v-ptiafn-": "x",
    "v-ptiafv-": "x",
    "v-stiafd-": "x",
    "v-stiafn-": "x",
    "v-stiafv-": "x",
    "v3stoe---": "x",
    "t-sf-pfa-": "x",
    "v3p------": "x",
    "t-df-pfa-": "x",
    "t-df-pfn-": "x",
    "t-df-pfv-": "x",
    "t-pf-pna-": "x",
    "t-pf-pnn-": "x",
    "t-pf-pnv-": "x",
    "t-sf-pfn-": "x",
    "t-sf-pfv-": "x",
    "v2daim---": "x",
    "v2damm---": "x",
    "t-da-ema-": "x",
    "t-da-emn-": "x",
    "t-da-emv-": "x",
    "t-da-ena-": "x",
    "t-da-enn-": "x",
    "t-da-env-": "x",
    "t-dp-mma-": "x",
    "t-dp-mmn-": "x",
    "t-dp-mmv-": "x",
    "t-dp-mna-": "x",
    "t-dp-mnn-": "x",
    "t-dp-mnv-": "x",
    "t-sa-mmv-": "x",
    "v2daoa---": "x",
    "t-dp-emd-": "x",
    "t-dp-emg-": "x",
    "t-dp-end-": "x",
    "t-dp-eng-": "x",
    "t-dr-emd-": "x",
    "t-dr-emg-": "x",
    "t-dr-end-": "x",
    "t-dr-eng-": "x",
    "t-dp-amd-": "x",
    "t-dp-amg-": "x",
    "t-dp-and-": "x",
    "t-dp-ang-": "x",
    "t-sp--na-": "x",
    "t-sp--nn-": "x",
    "t-sp--nv-": "x",
    "v2s-sa---": "x",
    "v3s-sa---": "x",
    "v2dlia---": "x",
    "v2plia---": "x",
    "a-p----a-": "x",
    "a-p----n-": "x",
    "a-p----v-": "x",
    "v2dam----": "x",
    "v2ptie---": "x",
    "t-da-efa-": "x",
    "t-da-efn-": "x",
    "t-da-efv-": "x",
    "t-pr-mfn-": "x",
    "t-pr-mfv-": "x",
    "t-sr-mfd-": "x",
    "t-sp-pfn-": "x",
    "t-sp-pfv-": "x",
    "v3sfop---": "x",
    "t--r-----": "x",
    "t-da-amd-": "x",
    "t-da-amg-": "x",
    "t-da-and-": "x",
    "t-da-ang-": "x",
    "v3ptim---": "x",
    "t-sf-mmv-": "x",
    "v3proa---": "x",
    "t-pf-emd-": "x",
    "t-pf-end-": "x",
    "t-sf-efa-": "x",
    "t-sf-emd-": "x",
    "t-sf-end-": "x",
    "t-st-efa-": "x",
    "t-st-emd-": "x",
    "t-st-end-": "x",
    "t-da-pfd-": "x",
    "t-da-pfg-": "x",
    "v3sfoe---": "x",
    "v1stoa---": "x",
    "v3pfop---": "x",
    "v3s------": "x",
    "t-pr-pfg-": "x",
    "t-pr-pmd-": "x",
    "t-pr-pmg-": "x",
    "t-pr-pmn-": "x",
    "t-pr-pmv-": "x",
    "t-pr-pnd-": "x",
    "t-pr-png-": "x",
    "v3ptoe---": "x",
    "v2dpoe---": "x",
    "t-pf-pmd-": "x",
    "t-pf-pnd-": "x",
    "v1siip---": "x",
    "v1srip---": "x",
    "v2piip---": "x",
    "v2ppip---": "x",
    "v2ppmp---": "x",
    "v2ppsp---": "x",
    "v2spip---": "x",
    "v2spsp---": "x",
    "v3spsp---": "x",
    "n-d---nd-": "x",
    "n-d---ng-": "x",
    "x-----n--": "x",
    "t-pp-pma-": "x",
    "v1piip---": "x",
    "v1ppsp---": "x",
    "v1spsp---": "x",
    "x-s----g-": "x",
    "x-s----n-": "x",
    "t-pp-mfa-": "x",
    "v2ppom---": "x",
    "t-st-efn-": "x",
    "t-st-efv-": "x",
    "v3prsa---": "x",
    "t-pt-mma-": "x",
    "v3ppmm---": "x",
    "v2dlie---": "x",
    "v2drie---": "x",
    "v3drie---": "x",
    "t-dp-pma-": "x",
    "t-dp-pmn-": "x",
    "t-dp-pmv-": "x",
    "t-dp-pna-": "x",
    "t-dp-pnn-": "x",
    "t-dp-pnv-": "x",
    "t-dr-pma-": "x",
    "t-dr-pmn-": "x",
    "t-dr-pmv-": "x",
    "t-dr-pna-": "x",
    "t-dr-pnn-": "x",
    "t-dr-pnv-": "x",
    "t-pp-pfn-": "x",
    "t-pp-pfv-": "x",
    "t-pp-pmd-": "x",
    "t-pp-pnd-": "x",
    "t-pr-pfn-": "x",
    "t-pr-pfv-": "x",
    "t-sp-pfa-": "x",
    "t-sp-pfd-": "x",
    "t-sp-pfg-": "x",
    "t-sp-pma-": "x",
    "t-sp-pmg-": "x",
    "t-sp-pna-": "x",
    "t-sp-png-": "x",
    "t-sp-pnn-": "x",
    "t-sp-pnv-": "x",
    "t-sr-pfa-": "x",
    "t-sr-pfd-": "x",
    "t-sr-pfg-": "x",
    "t-sr-pma-": "x",
    "t-sr-pmg-": "x",
    "t-sr-pna-": "x",
    "t-sr-png-": "x",
    "t-sr-pnn-": "x",
    "t-sr-pnv-": "x",
    "v2sao----": "x",
    "t-dr-amd-": "x",
    "t-dr-amg-": "x",
    "t-dr-and-": "x",
    "t-dr-ang-": "x",
    "a-d----dc": "x",
    "a-d----gc": "x",
    "d-----n--": "x",
    "t-dr-mfa-": "x",
    "t-dr-mfn-": "x",
    "t-dr-mfv-": "x",
    "t-pr-mna-": "x",
    "t-pr-mnn-": "x",
    "t-pr-mnv-": "x",
    "t-pp-an--": "x",
    "t-da-mmd-": "x",
    "t-da-mmg-": "x",
    "t-da-mnd-": "x",
    "t-da-mng-": "x",
    "t-dp-efd-": "x",
    "t-dp-efg-": "x",
    "v2dpse---": "x",
    "v3dpse---": "x",
    "t-dp-afd-": "x",
    "t-dp-afg-": "x",
    "v1sfop---": "x",
    "v1stip---": "x",
    "p-d---fv-": "x",
    "p-d---na-": "x",
    "p-d---nd-": "x",
    "p-d---ng-": "x",
    "p-d---nn-": "x",
    "p-d---nv-": "x",
    "p-p---fv-": "x",
    "p-p---mv-": "x",
    "p-p---nv-": "x",
    "a-d---mds": "x",
    "a-d---mgs": "x",
    "a-d---nds": "x",
    "a-d---ngs": "x",
    "t-dp-pfa-": "x",
    "t-dp-pfn-": "x",
    "t-dp-pfv-": "x",
    "t-pp-pna-": "x",
    "t-pp-pnn-": "x",
    "t-pp-pnv-": "x",
    "t-df-afd-": "x",
    "t-df-afg-": "x",
    "t-pp-mfd-": "x",
    "t-pa-efa-": "x",
    "v1stoe---": "x",
    "v2prse---": "x",
    "t-pa-efn-": "x",
    "t-pa-efv-": "x",
    "t-sa-efd-": "x",
    "t-df-efa-": "x",
    "t-df-efn-": "x",
    "t-df-efv-": "x",
    "t-pf-ena-": "x",
    "t-pf-enn-": "x",
    "t-pf-env-": "x",
    "t-sf-efn-": "x",
    "t-sf-efv-": "x",
    "v2sfoe---": "x",
    "v3srse---": "x",
    "v3dam----": "x",
    "v3pame---": "x",
    "t-pf-pfn-": "x",
    "t-pf-pfv-": "x",
    "t-sf-pfd-": "x",
    "t-sf-pmv-": "x",
    "t-pf-pfd-": "x",
    "v2dasm---": "x",
    "v3dasm---": "x",
    "v3dpoe---": "x",
    "t-st-mmn-": "x",
    "v1ptim---": "x",
    "m-d---fd-": "x",
    "m-d---fg-": "x",
    "m-d---md-": "x",
    "m-d---mg-": "x",
    "m-d---nd-": "x",
    "m-d---ng-": "x",
    "m-p---fd-": "x",
    "m-p---fg-": "x",
    "m-p---mg-": "x",
    "m-p---nd-": "x",
    "m-p---ng-": "x",
    "p1s----a-": "x",
    "p1s----n-": "x",
    "p1s----v-": "x",
    "p1d---fd-": "x",
    "p1d---fg-": "x",
    "p1d---md-": "x",
    "p1d---mg-": "x",
    "p1p---fd-": "x",
    "p1p---fg-": "x",
    "p1p---fn-": "x",
    "p1p---fv-": "x",
    "p1p---mv-": "x",
    "p1s---fv-": "x",
    "p1s---mv-": "x",
    "p3s----a-": "x",
    "v3daop---": "x",
    "v2dpsm---": "x",
    "v3dpsm---": "x",
    "t-pt-mmn-": "x",
    "t-pt-mmv-": "x",
    "v2ppop---": "x",
    "p1s---ng-": "x",
    "t-pf-efg-": "x",
    "t-pf-emg-": "x",
    "t-pf-eng-": "x",
    "t-df-mma-": "x",
    "t-df-mmn-": "x",
    "t-df-mmv-": "x",
    "t-df-mna-": "x",
    "t-df-mnn-": "x",
    "t-df-mnv-": "x",
    "v1plip---": "x",
    "v1prip---": "x",
    "v1slip---": "x",
    "v2dlip---": "x",
    "v2drip---": "x",
    "v2slip---": "x",
    "v2srip---": "x",
    "v2srmp---": "x",
    "v3dlip---": "x",
    "v3drip---": "x",
    "v3srmp---": "x",
    "v--pia---": "x",
    "v1proa---": "x",
    "v2drsa---": "x",
    "v3drma---": "x",
    "v3drsa---": "x",
    "x-s---fd-": "x",
    "t-sr-pmv-": "x",
    "t-pr-mfa-": "x",
    "t-sr-mfg-": "x",
    "t-pf-efa-": "x",
    "t-sf-efg-": "x",
    "v1p------": "x",
    "t-pp-pfg-": "x",
    "t-pp-pmg-": "x",
    "t-pp-png-": "x",
    "v2spop---": "x",
    "v2sa-m---": "x",
    "n-d----d-": "x",
    "n-d----g-": "x",
    "t-st-mmg-": "x",
    "t-st-mng-": "x",
    "v3daom---": "x",
    "t-pt-mfg-": "x",
    "t-pt-mmg-": "x",
    "t-pt-mng-": "x",
    "t-st-mma-": "x",
    "t-st-mna-": "x",
    "t-st-mnn-": "x",
    "t-st-mnv-": "x",
    "v3dpmm---": "x",
    "v3dpom---": "x",
    "v3ptom---": "x",
    "v3stom---": "x",
    "t-dr-mma-": "x",
    "t-dr-mmn-": "x",
    "t-dr-mmv-": "x",
    "t-dr-mna-": "x",
    "t-dr-mnn-": "x",
    "t-dr-mnv-": "x",
    "t-sr-mfa-": "x",
    "t-sr-mmd-": "x",
    "t-sr-mnd-": "x",
    "v2dlim---": "x",
    "v2drim---": "x",
    "v3drim---": "x",
    "v2dpom---": "x",
    "t-da-afd-": "x",
    "t-da-afg-": "x",
    "v3prma---": "x",
    "a-s----n-": "x",
    "a-s----v-": "x",
    "v2sroe---": "x",
    "x-s---n--": "x",
    "v3sroe---": "x",
    "t-pa-efd-": "x",
    "v3daie---": "x",
    "v3pfoe---": "x",
    "v1drie---": "x",
    "v2daie---": "x",
    "t-dr-afd-": "x",
    "t-dr-afg-": "x",
    "v1pfop---": "x",
    "v1ptom---": "x",
    "v1stom---": "x",
    "v2daop---": "x",
    "v2dfip---": "x",
    "v2dtim---": "x",
    "v2pfop---": "x",
    "v2ptom---": "x",
    "v2sfop---": "x",
    "v2stom---": "x",
    "v3dfip---": "x",
    "v3dtim---": "x",
    "v3ppsp---": "x",
    "t-sf-emv-": "x",
    "a-s----a-": "x",
    "v1srse---": "x",
    "p3s---na-": "x",
    "v--pme---": "x",
    "p-s---nv-": "x",
    "v1sfoe---": "x",
    "v2droa---": "x",
    "v3droa---": "x",
    "l-d---fd-": "x",
    "l-d---fn-": "x",
    "l-d---fv-": "x",
    "l-d---ma-": "x",
    "l-d---md-": "x",
    "l-d---mv-": "x",
    "l-d---nd-": "x",
    "l-d---ng-": "x",
    "l-d---nv-": "x",
    "l-p---fv-": "x",
    "l-p---mv-": "x",
    "l-p---nv-": "x",
    "l-s---fv-": "x",
    "l-s---nv-": "x",
    "a-s---f--": "x",
    "v1dpie---": "x",
    "v1dpsa---": "x",
    "d-s---ma-": "x",
    "p-s---fv-": "x",
    "t-dt-efa-": "x",
    "t-dt-efn-": "x",
    "t-dt-efv-": "x",
    "t-pt-ena-": "x",
    "t-pt-enn-": "x",
    "t-pt-env-": "x",
    "x-s---na-": "x",
    "x-s---nn-": "x",
    "x-s---nv-": "x",
    "v1dasa---": "x",
    "t-sp-mmv-": "x",
    "t-pp-pfa-": "x",
    "a-p---n--": "x",
    "n-----md-": "x",
    "t-sr-pmd-": "x",
    "t-sr-pnd-": "x",
    "v2p------": "x",
    "v1ppop---": "x",
    "v1spop---": "x",
    "v3diip---": "x",
    "v3ppop---": "x",
    "x-s---mv-": "x",
    "x-p------": "x",
    "v1pfoe---": "x",
    "p-p---n--": "x",
    "m-p---f--": "x",
    "m-p---n--": "x",
    "v2daom---": "x",
    "x-d----a-": "x",
    "x-d----d-": "x",
    "x-d----g-": "x",
    "x-d----n-": "x",
    "x-d----v-": "x",
    "x-p----g-": "x",
    "x-p---fa-": "x",
    "x-p---fn-": "x",
    "x-p---fv-": "x",
    "x-p---ma-": "x",
    "x-p---mn-": "x",
    "x-p---mv-": "x",
    "x-p---na-": "x",
    "x-p---nv-": "x",
    "x-s----d-": "x",
    "x-s---fa-": "x",
    "x-s---fn-": "x",
    "x-s---ma-": "x",
    "x-s---mn-": "x",
    "p-d----a-": "x",
    "p-d----g-": "x",
    "p-d----v-": "x",
    "a-----m--": "x",
    "m-p---fa-": "x",
    "m-p---fn-": "x",
    "m-p---fv-": "x",
    "m-p---ma-": "x",
    "m-p---mn-": "x",
    "m-p---mv-": "x",
    "m-p---na-": "x",
    "m-p---nv-": "x",
    "m-p----d-": "x",
    "m-p----g-": "x",
    "t-pt-efa-": "x",
    "t-st-efg-": "x",
    "v2stip---": "x",
    "v1p-sa---": "x",
    "v2d-sa---": "x",
    "v2p-sa---": "x",
    "v3d-sa---": "x",
    "v3p-sa---": "x",  # last one added to match morpheus. Review required. 
"---------" : "x",
"--p---fa-" : "x",
"--s---ma-" : "x",
"-3paia---" : "x",
"-3paim---" : "x",
"-3siia---" : "x",
"a--------" : "adj",
"a-------s" : "adj",
"a-d---fa-" : "adj",
"a-d---fd-" : "adj",
"a-d---fg-" : "adj",
"a-d---fn-" : "adj",
"a-d---ma-" : "adj",
"a-d---md-" : "adj",
"a-d---mg-" : "adj",
"a-d---mn-" : "adj",
"a-d---mnc" : "adj",
"a-d---mv-" : "adj",
"a-d---na-" : "adj",
"a-d---ng-" : "adj",
"a-d---nn-" : "adj",
"a-p----dc" : "adj",
"a-p---fa-" : "adj",
"a-p---fac" : "adj",
"a-p---fas" : "adj",
"a-p---fd-" : "adj",
"a-p---fdc" : "adj",
"a-p---fds" : "adj",
"a-p---fg-" : "adj",
"a-p---fgc" : "adj",
"a-p---fn-" : "adj",
"a-p---fnc" : "adj",
"a-p---fns" : "adj",
"a-p---fv-" : "adj",
"a-p---m--" : "adj",
"a-p---m-c" : "adj",
"a-p---ma-" : "adj",
"a-p---mac" : "adj",
"a-p---mas" : "adj",
"a-p---md-" : "adj",
"a-p---mdc" : "adj",
"a-p---mds" : "adj",
"a-p---mg-" : "adj",
"a-p---mgc" : "adj",
"a-p---mgs" : "adj",
"a-p---mn-" : "adj",
"a-p---mnc" : "adj",
"a-p---mns" : "adj",
"a-p---mv-" : "adj",
"a-p---mvs" : "adj",
"a-p---na-" : "adj",
"a-p---nac" : "adj",
"a-p---nas" : "adj",
"a-p---nd-" : "adj",
"a-p---ndc" : "adj",
"a-p---nds" : "adj",
"a-p---ng-" : "adj",
"a-p---ngs" : "adj",
"a-p---nn-" : "adj",
"a-p---nnc" : "adj",
"a-p---nns" : "adj",
"a-p---nv-" : "adj",
"a-s----d-" : "adj",
"a-s----dc" : "adj",
"a-s----g-" : "adj",
"a-s----gc" : "adj",
"a-s---fa-" : "adj",
"a-s---fac" : "adj",
"a-s---fas" : "adj",
"a-s---fd-" : "adj",
"a-s---fds" : "adj",
"a-s---fg-" : "adj",
"a-s---fgc" : "adj",
"a-s---fgs" : "adj",
"a-s---fn-" : "adj",
"a-s---fnc" : "adj",
"a-s---fns" : "adj",
"a-s---fv-" : "adj",
"a-s---m--" : "adj",
"a-s---ma-" : "adj",
"a-s---mac" : "adj",
"a-s---mas" : "adj",
"a-s---md-" : "adj",
"a-s---mdc" : "adj",
"a-s---mds" : "adj",
"a-s---mg-" : "adj",
"a-s---mgc" : "adj",
"a-s---mgs" : "adj",
"a-s---mn-" : "adj",
"a-s---mnc" : "adj",
"a-s---mns" : "adj",
"a-s---mv-" : "adj",
"a-s---mvc" : "adj",
"a-s---mvs" : "adj",
"a-s---na-" : "adj",
"a-s---nac" : "adj",
"a-s---nas" : "adj",
"a-s---nd-" : "adj",
"a-s---ndc" : "adj",
"a-s---nds" : "adj",
"a-s---ng-" : "adj",
"a-s---nn-" : "adj",
"a-s---nnc" : "adj",
"a-s---nns" : "adj",
"a-s---nv-" : "adj",
"a-s---nvs" : "adj",
"c--------" : "cconj",
"c--------" : "sconj",
"d--------" : "adv",
"d-------c" : "adv",
"d-------s" : "adv",
"g--------" : "part",
"i--------" : "intj",
"l--------" : "det",
"l-d---fa-" : "det",
"l-d---fg-" : "det",
"l-d---mg-" : "det",
"l-d---mn-" : "det",
"l-d---na-" : "det",
"l-d---nn-" : "det",
"l-p---fa-" : "det",
"l-p---fd-" : "det",
"l-p---fg-" : "det",
"l-p---fn-" : "det",
"l-p---ma-" : "det",
"l-p---md-" : "det",
"l-p---mg-" : "det",
"l-p---mn-" : "det",
"l-p---na-" : "det",
"l-p---nd-" : "det",
"l-p---ng-" : "det",
"l-p---nn-" : "det",
"l-s---fa-" : "det",
"l-s---fd-" : "det",
"l-s---fg-" : "det",
"l-s---fn-" : "det",
"l-s---ma-" : "det",
"l-s---md-" : "det",
"l-s---mg-" : "det",
"l-s---mn-" : "det",
"l-s---na-" : "det",
"l-s---nd-" : "det",
"l-s---ng-" : "det",
"l-s---nn-" : "det",
"m--------" : "num",
"m-p---m--" : "num",
"m-p---md-" : "num",
"m-p---nn-" : "num",
"n-----fg-" : "noun",
"n-----na-" : "noun",
"n-----nn-" : "noun",
"n-d----a-" : "noun",
"n-d---fa-" : "noun",
"n-d---fd-" : "noun",
"n-d---fg-" : "noun",
"n-d---fn-" : "noun",
"n-d---ma-" : "noun",
"n-d---md-" : "noun",
"n-d---mg-" : "noun",
"n-d---mn-" : "noun",
"n-d---mv-" : "noun",
"n-d---na-" : "noun",
"n-d---nn-" : "noun",
"n-p----d-" : "noun",
"n-p----g-" : "noun",
"n-p---fa-" : "noun",
"n-p---fd-" : "noun",
"n-p---fg-" : "noun",
"n-p---fn-" : "noun",
"n-p---fv-" : "noun",
"n-p---ma-" : "noun",
"n-p---md-" : "noun",
"n-p---mg-" : "noun",
"n-p---mn-" : "noun",
"n-p---mv-" : "noun",
"n-p---na-" : "noun",
"n-p---nd-" : "noun",
"n-p---ng-" : "noun",
"n-p---nn-" : "noun",
"n-p---nv-" : "noun",
"n-s----d-" : "noun",
"n-s----g-" : "noun",
"n-s----n-" : "noun",
"n-s----v-" : "noun",
"n-s---fa-" : "noun",
"n-s---fd-" : "noun",
"n-s---fg-" : "noun",
"n-s---fn-" : "noun",
"n-s---fv-" : "noun",
"n-s---m--" : "noun",
"n-s---ma-" : "noun",
"n-s---md-" : "noun",
"n-s---mg-" : "noun",
"n-s---mn-" : "noun",
"n-s---mv-" : "noun",
"n-s---na-" : "noun",
"n-s---nd-" : "noun",
"n-s---ng-" : "noun",
"n-s---nn-" : "noun",
"n-s---nv-" : "noun",
"p--------" : "pron",
"p-d----d-" : "pron",
"p-d----n-" : "pron",
"p-d---fa-" : "pron",
"p-d---fd-" : "pron",
"p-d---fg-" : "pron",
"p-d---fn-" : "pron",
"p-d---ma-" : "pron",
"p-d---md-" : "pron",
"p-d---mg-" : "pron",
"p-d---mn-" : "pron",
"p-d---mv-" : "pron",
"p-p----a-" : "pron",
"p-p----d-" : "pron",
"p-p----g-" : "pron",
"p-p----n-" : "pron",
"p-p---fa-" : "pron",
"p-p---fd-" : "pron",
"p-p---fg-" : "pron",
"p-p---fn-" : "pron",
"p-p---ma-" : "pron",
"p-p---md-" : "pron",
"p-p---mg-" : "pron",
"p-p---mn-" : "pron",
"p-p---na-" : "pron",
"p-p---nd-" : "pron",
"p-p---ng-" : "pron",
"p-p---nn-" : "pron",
"p-s----a-" : "pron",
"p-s----d-" : "pron",
"p-s----g-" : "pron",
"p-s----n-" : "pron",
"p-s---fa-" : "pron",
"p-s---fd-" : "pron",
"p-s---fg-" : "pron",
"p-s---fn-" : "pron",
"p-s---ma-" : "pron",
"p-s---md-" : "pron",
"p-s---mg-" : "pron",
"p-s---mn-" : "pron",
"p-s---mv-" : "pron",
"p-s---na-" : "pron",
"p-s---nd-" : "pron",
"p-s---ng-" : "pron",
"p-s---nn-" : "pron",
"p1p---fa-" : "pron",
"p1p---ma-" : "pron",
"p1p---md-" : "pron",
"p1p---mg-" : "pron",
"p1p---mn-" : "pron",
"p1s---fa-" : "pron",
"p1s---fd-" : "pron",
"p1s---fg-" : "pron",
"p1s---fn-" : "pron",
"p1s---ma-" : "pron",
"p1s---md-" : "pron",
"p1s---mg-" : "pron",
"p1s---mn-" : "pron",
"p2p----a-" : "pron",
"p2p----d-" : "pron",
"p2p---ma-" : "pron",
"p2p---mg-" : "pron",
"p2p---mn-" : "pron",
"p2s----a-" : "pron",
"p2s----d-" : "pron",
"p2s----g-" : "pron",
"p2s----n-" : "pron",
"p2s---ma-" : "pron",
"p2s---md-" : "pron",
"p2s---mg-" : "pron",
"p3s---fa-" : "pron",
"p3s---ma-" : "pron",
"r--------" : "adp",
"u--------" : "punct",
"v---na---" : "verb",
"v--amm---" : "verb",
"v--an----" : "verb",
"v--ana---" : "verb",
"v--ane---" : "verb",
"v--anm---" : "verb",
"v--anp---" : "verb",
"v--fna---" : "verb",
"v--fne---" : "verb",
"v--fnm---" : "verb",
"v--fnp---" : "verb",
"v--pna---" : "verb",
"v--pnd---" : "verb",
"v--pne---" : "verb",
"v--pnp---" : "verb",
"v--ppefa-" : "verb",
"v--ppemn-" : "verb",
"v--rn----" : "verb",
"v--rna---" : "verb",
"v--rne---" : "verb",
"v--rnp---" : "verb",
"v--tna---" : "verb",
"v-dapafn-" : "verb",
"v-dapama-" : "verb",
"v-dapamg-" : "verb",
"v-dapamn-" : "verb",
"v-dapmfn-" : "verb",
"v-dapmmn-" : "verb",
"v-dappma-" : "verb",
"v-dappmn-" : "verb",
"v-dppafg-" : "verb",
"v-dppama-" : "verb",
"v-dppamn-" : "verb",
"v-dppefn-" : "verb",
"v-dppema-" : "verb",
"v-dppemd-" : "verb",
"v-dppemn-" : "verb",
"v-dpppmn-" : "verb",
"v-drpama-" : "verb",
"v-drpamn-" : "verb",
"v-drpefn-" : "verb",
"v-drpemn-" : "verb",
"v-p-pmma-" : "verb",
"v-pap-mn-" : "verb",
"v-papafa-" : "verb",
"v-papafg-" : "verb",
"v-papafn-" : "verb",
"v-papama-" : "verb",
"v-papamd-" : "verb",
"v-papamg-" : "verb",
"v-papamn-" : "verb",
"v-papana-" : "verb",
"v-papand-" : "verb",
"v-papann-" : "verb",
"v-papefn-" : "verb",
"v-papema-" : "verb",
"v-papemn-" : "verb",
"v-papmfa-" : "verb",
"v-papmfg-" : "verb",
"v-papmfn-" : "verb",
"v-papmma-" : "verb",
"v-papmmd-" : "verb",
"v-papmmg-" : "verb",
"v-papmmn-" : "verb",
"v-papmna-" : "verb",
"v-papmng-" : "verb",
"v-papmnn-" : "verb",
"v-pappfd-" : "verb",
"v-pappfg-" : "verb",
"v-pappfn-" : "verb",
"v-pappma-" : "verb",
"v-pappmd-" : "verb",
"v-pappmg-" : "verb",
"v-pappmn-" : "verb",
"v-pappna-" : "verb",
"v-pappng-" : "verb",
"v-pappnn-" : "verb",
"v-pfpama-" : "verb",
"v-pfpamg-" : "verb",
"v-pfpamn-" : "verb",
"v-pfpema-" : "verb",
"v-pfpemn-" : "verb",
"v-pfpmfa-" : "verb",
"v-pfpmfn-" : "verb",
"v-pfpmma-" : "verb",
"v-pfpmmd-" : "verb",
"v-pfpmmg-" : "verb",
"v-pfpmmn-" : "verb",
"v-pfpmnn-" : "verb",
"v-pfppmn-" : "verb",
"v-ppp-mn-" : "verb",
"v-pppafa-" : "verb",
"v-pppafd-" : "verb",
"v-pppafg-" : "verb",
"v-pppafn-" : "verb",
"v-pppafv-" : "verb",
"v-pppama-" : "verb",
"v-pppamd-" : "verb",
"v-pppamg-" : "verb",
"v-pppamn-" : "verb",
"v-pppamv-" : "verb",
"v-pppana-" : "verb",
"v-pppand-" : "verb",
"v-pppang-" : "verb",
"v-pppann-" : "verb",
"v-pppefa-" : "verb",
"v-pppefd-" : "verb",
"v-pppefg-" : "verb",
"v-pppefn-" : "verb",
"v-pppefv-" : "verb",
"v-pppema-" : "verb",
"v-pppemd-" : "verb",
"v-pppemg-" : "verb",
"v-pppemn-" : "verb",
"v-pppemv-" : "verb",
"v-pppena-" : "verb",
"v-pppend-" : "verb",
"v-pppeng-" : "verb",
"v-pppenn-" : "verb",
"v-ppppma-" : "verb",
"v-ppppmd-" : "verb",
"v-ppppmn-" : "verb",
"v-prp-mn-" : "verb",
"v-prpafa-" : "verb",
"v-prpafd-" : "verb",
"v-prpafn-" : "verb",
"v-prpama-" : "verb",
"v-prpamd-" : "verb",
"v-prpamg-" : "verb",
"v-prpamn-" : "verb",
"v-prpana-" : "verb",
"v-prpang-" : "verb",
"v-prpefa-" : "verb",
"v-prpefd-" : "verb",
"v-prpefg-" : "verb",
"v-prpefn-" : "verb",
"v-prpema-" : "verb",
"v-prpemd-" : "verb",
"v-prpemg-" : "verb",
"v-prpemn-" : "verb",
"v-prpena-" : "verb",
"v-prpend-" : "verb",
"v-prpeng-" : "verb",
"v-prpenn-" : "verb",
"v-prppfn-" : "verb",
"v-prppmn-" : "verb",
"v-sagamn-" : "verb",
"v-saiamn-" : "verb",
"v-samp---" : "verb",
"v-sap-mg-" : "verb",
"v-sap-mn-" : "verb",
"v-sapafa-" : "verb",
"v-sapafd-" : "verb",
"v-sapafg-" : "verb",
"v-sapafn-" : "verb",
"v-sapama-" : "verb",
"v-sapamd-" : "verb",
"v-sapamg-" : "verb",
"v-sapamn-" : "verb",
"v-sapamv-" : "verb",
"v-sapana-" : "verb",
"v-sapang-" : "verb",
"v-sapann-" : "verb",
"v-sapanv-" : "verb",
"v-sapema-" : "verb",
"v-sapemn-" : "verb",
"v-sapmfa-" : "verb",
"v-sapmfd-" : "verb",
"v-sapmfg-" : "verb",
"v-sapmfn-" : "verb",
"v-sapmma-" : "verb",
"v-sapmmd-" : "verb",
"v-sapmmg-" : "verb",
"v-sapmmn-" : "verb",
"v-sapmna-" : "verb",
"v-sapmng-" : "verb",
"v-sapmnn-" : "verb",
"v-sappfa-" : "verb",
"v-sappfd-" : "verb",
"v-sappfg-" : "verb",
"v-sappfn-" : "verb",
"v-sappma-" : "verb",
"v-sappmd-" : "verb",
"v-sappmg-" : "verb",
"v-sappmn-" : "verb",
"v-sappna-" : "verb",
"v-sappng-" : "verb",
"v-sappnn-" : "verb",
"v-sappnv-" : "verb",
"v-sfpafa-" : "verb",
"v-sfpafd-" : "verb",
"v-sfpafn-" : "verb",
"v-sfpama-" : "verb",
"v-sfpamd-" : "verb",
"v-sfpamg-" : "verb",
"v-sfpamn-" : "verb",
"v-sfpmfa-" : "verb",
"v-sfpmfd-" : "verb",
"v-sfpmfg-" : "verb",
"v-sfpmfn-" : "verb",
"v-sfpmma-" : "verb",
"v-sfpmmg-" : "verb",
"v-sfpmmn-" : "verb",
"v-sfpmna-" : "verb",
"v-sfppma-" : "verb",
"v-spiamn-" : "verb",
"v-spp-mn-" : "verb",
"v-spp-nn-" : "verb",
"v-sppa---" : "verb",
"v-sppafa-" : "verb",
"v-sppafd-" : "verb",
"v-sppafg-" : "verb",
"v-sppafn-" : "verb",
"v-sppafv-" : "verb",
"v-sppama-" : "verb",
"v-sppamd-" : "verb",
"v-sppamg-" : "verb",
"v-sppamn-" : "verb",
"v-sppamv-" : "verb",
"v-sppana-" : "verb",
"v-sppand-" : "verb",
"v-sppang-" : "verb",
"v-sppann-" : "verb",
"v-sppanv-" : "verb",
"v-sppefa-" : "verb",
"v-sppefd-" : "verb",
"v-sppefg-" : "verb",
"v-sppefn-" : "verb",
"v-sppema-" : "verb",
"v-sppemd-" : "verb",
"v-sppemg-" : "verb",
"v-sppemn-" : "verb",
"v-sppemv-" : "verb",
"v-sppena-" : "verb",
"v-sppend-" : "verb",
"v-sppeng-" : "verb",
"v-sppenn-" : "verb",
"v-spppfa-" : "verb",
"v-spppfd-" : "verb",
"v-spppfg-" : "verb",
"v-spppfn-" : "verb",
"v-spppma-" : "verb",
"v-spppmn-" : "verb",
"v-srp-mn-" : "verb",
"v-srpafa-" : "verb",
"v-srpafd-" : "verb",
"v-srpafg-" : "verb",
"v-srpafn-" : "verb",
"v-srpama-" : "verb",
"v-srpamd-" : "verb",
"v-srpamg-" : "verb",
"v-srpamn-" : "verb",
"v-srpamv-" : "verb",
"v-srpana-" : "verb",
"v-srpand-" : "verb",
"v-srpang-" : "verb",
"v-srpann-" : "verb",
"v-srpefa-" : "verb",
"v-srpefd-" : "verb",
"v-srpefg-" : "verb",
"v-srpefn-" : "verb",
"v-srpema-" : "verb",
"v-srpemd-" : "verb",
"v-srpemg-" : "verb",
"v-srpemn-" : "verb",
"v-srpemv-" : "verb",
"v-srpena-" : "verb",
"v-srpend-" : "verb",
"v-srpeng-" : "verb",
"v-srpenn-" : "verb",
"v-srppfn-" : "verb",
"v-srppma-" : "verb",
"v-srppmn-" : "verb",
"v-srppmv-" : "verb",
"v1paia---" : "verb",
"v1paim---" : "verb",
"v1paip---" : "verb",
"v1paoa---" : "verb",
"v1paom---" : "verb",
"v1paop---" : "verb",
"v1pasa---" : "verb",
"v1pase---" : "verb",
"v1pasm---" : "verb",
"v1pasp---" : "verb",
"v1pfia---" : "verb",
"v1pfim---" : "verb",
"v1pfom---" : "verb",
"v1piia---" : "verb",
"v1piie---" : "verb",
"v1plia---" : "verb",
"v1plie---" : "verb",
"v1ppia---" : "verb",
"v1ppie---" : "verb",
"v1ppip---" : "verb",
"v1ppoa---" : "verb",
"v1ppoe---" : "verb",
"v1ppsa---" : "verb",
"v1ppse---" : "verb",
"v1pria---" : "verb",
"v1prie---" : "verb",
"v1prsa---" : "verb",
"v1prse---" : "verb",
"v1ptie---" : "verb",
"v1s-sa---" : "verb",
"v1sa-a---" : "verb",
"v1saia---" : "verb",
"v1saie---" : "verb",
"v1saim---" : "verb",
"v1saip---" : "verb",
"v1sao----" : "verb",
"v1saoa---" : "verb",
"v1saoe---" : "verb",
"v1saom---" : "verb",
"v1saop---" : "verb",
"v1sasa---" : "verb",
"v1sase---" : "verb",
"v1sasm---" : "verb",
"v1sasp---" : "verb",
"v1sfi----" : "verb",
"v1sfia---" : "verb",
"v1sfie---" : "verb",
"v1sfim---" : "verb",
"v1sfip---" : "verb",
"v1siia---" : "verb",
"v1siie---" : "verb",
"v1slia---" : "verb",
"v1slie---" : "verb",
"v1slim---" : "verb",
"v1spia---" : "verb",
"v1spie---" : "verb",
"v1spoa---" : "verb",
"v1spoe---" : "verb",
"v1spsa---" : "verb",
"v1spse---" : "verb",
"v1sria---" : "verb",
"v1srie---" : "verb",
"v1sroa---" : "verb",
"v1sroe---" : "verb",
"v1srsa---" : "verb",
"v1stie---" : "verb",
"v1stim---" : "verb",
"v2daia---" : "verb",
"v2dama---" : "verb",
"v2dasa---" : "verb",
"v2dase---" : "verb",
"v2dfia---" : "verb",
"v2dfim---" : "verb",
"v2diia---" : "verb",
"v2diie---" : "verb",
"v2dpia---" : "verb",
"v2dpma---" : "verb",
"v2dpme---" : "verb",
"v2dria---" : "verb",
"v2drma---" : "verb",
"v2paia---" : "verb",
"v2paim---" : "verb",
"v2paip---" : "verb",
"v2pama---" : "verb",
"v2pame---" : "verb",
"v2pamm---" : "verb",
"v2paoa---" : "verb",
"v2paom---" : "verb",
"v2paop---" : "verb",
"v2pasa---" : "verb",
"v2pase---" : "verb",
"v2pasm---" : "verb",
"v2pasp---" : "verb",
"v2pfia---" : "verb",
"v2pfim---" : "verb",
"v2piia---" : "verb",
"v2piie---" : "verb",
"v2ppia---" : "verb",
"v2ppie---" : "verb",
"v2ppma---" : "verb",
"v2ppme---" : "verb",
"v2ppoa---" : "verb",
"v2ppoe---" : "verb",
"v2ppsa---" : "verb",
"v2pria---" : "verb",
"v2prie---" : "verb",
"v2prma---" : "verb",
"v2prmp---" : "verb",
"v2proa---" : "verb",
"v2prsa---" : "verb",
"v2saia---" : "verb",
"v2saie---" : "verb",
"v2saim---" : "verb",
"v2saip---" : "verb",
"v2sam----" : "verb",
"v2sama---" : "verb",
"v2same---" : "verb",
"v2samm---" : "verb",
"v2samp---" : "verb",
"v2saoa---" : "verb",
"v2saoe---" : "verb",
"v2saom---" : "verb",
"v2saop---" : "verb",
"v2sasa---" : "verb",
"v2sase---" : "verb",
"v2sasm---" : "verb",
"v2sasp---" : "verb",
"v2sfi----" : "verb",
"v2sfia---" : "verb",
"v2sfie---" : "verb",
"v2sfim---" : "verb",
"v2sfip---" : "verb",
"v2siia---" : "verb",
"v2siie---" : "verb",
"v2siip---" : "verb",
"v2slia---" : "verb",
"v2slie---" : "verb",
"v2slim---" : "verb",
"v2spia---" : "verb",
"v2spie---" : "verb",
"v2spma---" : "verb",
"v2spme---" : "verb",
"v2spoa---" : "verb",
"v2spoe---" : "verb",
"v2spsa---" : "verb",
"v2spse---" : "verb",
"v2sria---" : "verb",
"v2srie---" : "verb",
"v2srma---" : "verb",
"v2srme---" : "verb",
"v2sroa---" : "verb",
"v2srsa---" : "verb",
"v2stie---" : "verb",
"v3-roe---" : "verb",
"v3daia---" : "verb",
"v3daim---" : "verb",
"v3daip---" : "verb",
"v3daoa---" : "verb",
"v3dfia---" : "verb",
"v3dfim---" : "verb",
"v3diia---" : "verb",
"v3diie---" : "verb",
"v3dlia---" : "verb",
"v3dlie---" : "verb",
"v3dlim---" : "verb",
"v3dpia---" : "verb",
"v3dpie---" : "verb",
"v3dpma---" : "verb",
"v3dpme---" : "verb",
"v3dpsa---" : "verb",
"v3dria---" : "verb",
"v3pai----" : "verb",
"v3paia---" : "verb",
"v3paie---" : "verb",
"v3paim---" : "verb",
"v3paip---" : "verb",
"v3pamm---" : "verb",
"v3paoa---" : "verb",
"v3paoe---" : "verb",
"v3paom---" : "verb",
"v3paop---" : "verb",
"v3pasa---" : "verb",
"v3pase---" : "verb",
"v3pasm---" : "verb",
"v3pasp---" : "verb",
"v3pfia---" : "verb",
"v3pfie---" : "verb",
"v3pfim---" : "verb",
"v3piia---" : "verb",
"v3piie---" : "verb",
"v3piip---" : "verb",
"v3plia---" : "verb",
"v3plie---" : "verb",
"v3plim---" : "verb",
"v3plip---" : "verb",
"v3ppia---" : "verb",
"v3ppie---" : "verb",
"v3ppip---" : "verb",
"v3ppma---" : "verb",
"v3ppme---" : "verb",
"v3ppoa---" : "verb",
"v3ppoe---" : "verb",
"v3ppsa---" : "verb",
"v3ppse---" : "verb",
"v3pria---" : "verb",
"v3prie---" : "verb",
"v3prip---" : "verb",
"v3sai----" : "verb",
"v3saia---" : "verb",
"v3saie---" : "verb",
"v3saim---" : "verb",
"v3saip---" : "verb",
"v3sama---" : "verb",
"v3samm---" : "verb",
"v3samp---" : "verb",
"v3sana---" : "verb",
"v3sao----" : "verb",
"v3saoa---" : "verb",
"v3saoe---" : "verb",
"v3saom---" : "verb",
"v3saop---" : "verb",
"v3sas----" : "verb",
"v3sasa---" : "verb",
"v3sase---" : "verb",
"v3sasm---" : "verb",
"v3sasp---" : "verb",
"v3sfi----" : "verb",
"v3sfia---" : "verb",
"v3sfie---" : "verb",
"v3sfim---" : "verb",
"v3sfip---" : "verb",
"v3sfoa---" : "verb",
"v3sii----" : "verb",
"v3siia---" : "verb",
"v3siie---" : "verb",
"v3siip---" : "verb",
"v3sli----" : "verb",
"v3slia---" : "verb",
"v3slie---" : "verb",
"v3slim---" : "verb",
"v3slip---" : "verb",
"v3spia---" : "verb",
"v3spie---" : "verb",
"v3spip---" : "verb",
"v3spma---" : "verb",
"v3spme---" : "verb",
"v3spoa---" : "verb",
"v3spoe---" : "verb",
"v3spop---" : "verb",
"v3spsa---" : "verb",
"v3spse---" : "verb",
"v3sria---" : "verb",
"v3srie---" : "verb",
"v3srip---" : "verb",
"v3srma---" : "verb",
"v3sroa---" : "verb",
"v3srsa---" : "verb",
"v3stie---" : "verb",
"v3stim---" : "verb",
"v3stip---" : "verb",
"x--------" : "x",
"x-p----d-" : "x",
"x-p---nn-" : "x",
}


def buildictmorpheus(context):
    corpus = dict() # creates the dictionary for the corpus

    i = 0

    for event, elem in context:
    
        univpos = univ_pos_name_variants[elem[5].text]  # <morphological-analysis>a-s---fa-</morphological-analysis>
        form = elem[1].text                             # <word-form>ἀάατον</word-form>
        lemma = elem[3].text                            # <lemma>ἀάατος</lemma>
        print(form, univpos, lemma)     
        if form in corpus and univpos in corpus[form] and not lemma == corpus[form][univpos]:
           print(i, "Alert!. Replacing previous assignment of ", form, univpos, corpus[form][univpos], " with ", lemma) 
           new_value =  { univpos : lemma } 
           corpus.update({ form : new_value } )
        else:     
           corpus.update({ form : { univpos: lemma }  })
       
        print(i)
        i+=1
        # It's safe to call clear() here because no descendants will be accessed
        elem.clear(keep_tail=True)
 
        # Also eliminate now-empty references from the root node to <Title> 
        while elem.getprevious() is not None:
            del elem.getparent()[0]

    corpus = collections.OrderedDict(sorted(corpus.items()))
    
    return corpus
    

def buildindexmorpheus(context):
    index = dict()
    
    for event, elem in context:
        pos = elem[5].text                              # <morphological-analysis>a-s---fa-</morphological-analysis>
        form = elem[1].text                             # <word-form>ἀάατον</word-form>
        lemma = elem[3].text                            # <lemma>ἀάατος</lemma>
        
        univpos = univ_pos_name_variants[pos]
        lemmas = [lemma]
        if univpos in index:
            first_lemmas = index[univpos]
            if lemma not in first_lemmas: 
                index.update({ univpos : first_lemmas+lemmas })
        else:
            index.update({ univpos : lemmas })    
       
        # It's safe to call clear() here because no descendants will be accessed
        elem.clear(keep_tail=True)                            
                
    return index

def buildposmorpheus(context):
    index = dict()
    
    for event, elem in context:
        pos = elem[5].text                              # <morphological-analysis>a-s---fa-</morphological-analysis>
        form = elem[1].text                             # <word-form>ἀάατον</word-form>
        lemma = elem[3].text                            # <lemma>ἀάατος</lemma>
        
        if pos in univ_pos_name_variants or pos in index:
            pass
        else:
            index.update({ pos : "x" })
            print('\"', pos, "\" : \"x\"")    
       
        # It's safe to call clear() here because no descendants will be accessed
        elem.clear(keep_tail=True)                            
                
    return index

  
def main(argv):
    infile = ''
    outfile = ''
    #func = buildposmorpheus
    #print(argv)
    try:
        opts, args = getopt.gnu_getopt(argv,"hpnci:o:",["pos", "index", "corpus","ifile=","ofile="])
        #print(opts, args)
    except getopt.GetoptError:
        print('readingbigcorpus.py --<pos|index|corpus> -i <inputfile> -o <outputfile>')
        sys.exit(2)
    for opt, arg in opts:
        if opt == '-h':
            print('readingbigcorpus.py --<pos|index|corpus> -i <inputfile> -o <outputfile>')
            sys.exit()
        elif opt in ("-p", "--pos"):
            func = buildposmorpheus
            print("Building the pos file")
        elif opt in ("-n", "--index"):
            func = buildindexmorpheus
            print("Building the index")
        elif opt in ("-c", "--corpus"):
            func = buildictmorpheus 
            print("Building lemma_lookup")    
        elif opt in ("-i", "--ifile"):
            infile = arg
            print("from file", infile)  
        elif opt in ("-o", "--ofile"):
            outfile = arg
            print("on file", outfile)  
    
    
    #print(func, infile, outfile)
         
    context = etree.iterparse(infile, events=('end',), tag='t')

    print('\nStart of corpus generation:')
     
    data = func(context)

    print("Data size:", len(data))

    with open(outfile, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=4)

    print('\nEnd of corpus generation:')


if __name__ == "__main__":
   main(sys.argv[1:])


