#!/usr/bin/python
# readingbigcorpusapart.py
# based on https://www.ibm.com/developerworks/xml/library/x-hiperfparse/
# Usage: 
# python ./readingbigcorpusapart.py --report -i MorpheusUnicode.xml -o empty.json
# python ./readingbigcorpusapart.py --pos -i MorpheusUnicode.xml -o pos.json
# python ./readingbigcorpusapart.py --index -i MorpheusUnicode.xml -o index.json
# python ./readingbigcorpusapart.py --corpus -i MorpheusUnicode.xml 
# Please notice this last produces many lemma_lookup files, one for every pos being used. 

from lxml import etree
import json 
import collections
import sys, getopt
import csv
import requests 

#results = etree.parse(infile, parser)    
 
# When iterated over, 'results' will contain the output from 
# target parser's close() method
 
#out = open('titles.txt', 'w')
#out.write('\n'.join(results))
#out.close()

univ_pos_name_variants = {
"a-d---fv-" : "adj",  # added after curing
"a-d---nv-" : "adj",
"a-p---ngc" : "adj",
"a-d---fas" : "adj",
"a-d---fns" : "adj",
"a-d---fvs" : "adj",
"a-p---nvs" : "adj",
"a-s---fvs" : "adj",
"a-s---nvc" : "adj",
"a-d---fac" : "adj",
"a-d---fnc" : "adj",
"a-d---fvc" : "adj",
"a-p---nvc" : "adj",
"a-s---fvc" : "adj",
"a-d---nd-" : "adj",
"a-p---fvs" : "adj",
"a-p---fgs" : "adj",
"a-p---fvc" : "adj",
"a-s---fdc" : "adj",
"a-d----a-" : "adj",
"a-d----n-" : "adj",
"a-d----v-" : "adj",
"a-d---mas" : "adj",
"a-d---mns" : "adj",
"a-d---mvs" : "adj",
"a-d---nas" : "adj",
"a-d---nns" : "adj",
"a-d---nvs" : "adj",
"a-p----d-" : "adj",
"a-s---ngs" : "adj",
"a-p---mvc" : "adj",
"r-------c" : "adp",
"a-s---ngc" : "adj",
"a-p----gc" : "adj",
"a-d---mac" : "adj",
"a-d---mvc" : "adj",
"a-d---nac" : "adj",
"a-d---nnc" : "adj",
"a-d---nvc" : "adj",
"a-------c" : "adj",
"a-d----d-" : "adj",
"a-d----g-" : "adj",
"a-d----ac" : "adj",
"a-d----nc" : "adj",
"a-d----vc" : "adj",
"a-p----g-" : "adj",
"a-p----a-" : "adj",
"a-p----n-" : "adj",
"a-p----v-" : "adj",
"a-d----dc" : "adj",
"a-d----gc" : "adj",
"d-----n--" : "adj",
"a-d---mds" : "adj",
"a-d---mgs" : "adj",
"a-d---nds" : "adj",
"a-d---ngs" : "adj",
"a-s----n-" : "adj",
"a-s----v-" : "adj",
"a-s----a-" : "adj",
"l-d---fd-" : "adj",
"l-d---fn-" : "adj",
"l-d---fv-" : "adj",
"l-d---ma-" : "adj",
"l-d---md-" : "adj",
"l-d---mv-" : "adj",
"l-d---nd-" : "adj",
"l-d---ng-" : "adj",
"l-d---nv-" : "adj",
"l-p---fv-" : "adj",
"l-p---mv-" : "adj",
"l-p---nv-" : "adj",
"l-s---fv-" : "adj",
"l-s---nv-" : "adj",
"a-s---f--" : "adj",
"d-s---ma-" : "adj",
"a-p---n--" : "adj",
"a-----m--" : "adj",
"e--------" : "intj",
"n--------" : "noun",
"n-d---fv-" : "noun",
"n-d---nv-" : "noun",
"n-d----n-" : "noun",
"n-d----v-" : "noun",
"n-p----a-" : "noun",
"n-p----n-" : "noun",
"n-p----v-" : "noun",
"n-s----a-" : "noun",
"n-----nv-" : "noun",
"n-d---nd-" : "noun",
"n-d---ng-" : "noun",
"n-d----d-" : "noun",
"n-d----g-" : "noun",
"n-----md-" : "noun",
"m-d---fd-" : "num",
"m-d---fg-" : "num",
"m-d---md-" : "num",
"m-d---mg-" : "num",
"m-d---nd-" : "num",
"m-d---ng-" : "num",
"m-p---fd-" : "num",
"m-p---fg-" : "num",
"m-p---mg-" : "num",
"m-p---nd-" : "num",
"m-p---ng-" : "num",
"m-p---f--" : "num",
"m-p---n--" : "num",
"m-p---fa-" : "num",
"m-p---fn-" : "num",
"m-p---fv-" : "num",
"m-p---ma-" : "num",
"m-p---mn-" : "num",
"m-p---mv-" : "num",
"m-p---na-" : "num",
"m-p---nv-" : "num",
"m-p----d-" : "num",
"m-p----g-" : "num",
"p-d---fv-" : "pron",
"p-d---na-" : "pron",
"p-d---nd-" : "pron",
"p-d---ng-" : "pron",
"p-d---nn-" : "pron",
"p-d---nv-" : "pron",
"p-p---fv-" : "pron",
"p-p---mv-" : "pron",
"p-p---nv-" : "pron",
"p1s----a-" : "pron",
"p1s----n-" : "pron",
"p1s----v-" : "pron",
"p1d---fd-" : "pron",
"p1d---fg-" : "pron",
"p1d---md-" : "pron",
"p1d---mg-" : "pron",
"p1p---fd-" : "pron",
"p1p---fg-" : "pron",
"p1p---fn-" : "pron",
"p1p---fv-" : "pron",
"p1p---mv-" : "pron",
"p1s---fv-" : "pron",
"p1s---mv-" : "pron",
"p3s----a-" : "pron",
"p1s---ng-" : "pron",
"p3s---na-" : "pron",
"p-s---nv-" : "pron",
"p-s---fv-" : "pron",
"p-p---n--" : "pron",
"p-d----a-" : "pron",
"p-d----g-" : "pron",
"p-d----v-" : "pron",
"t-dp-afa-" : "verb",
"t-dp-afn-" : "verb",
"t-dp-afv-" : "verb",
"t-pp-afa-" : "verb",
"t-pp-afg-" : "verb",
"t-pp-afn-" : "verb",
"t-pp-afv-" : "verb",
"t-pp-amd-" : "verb",
"t-pp-and-" : "verb",
"t-sa-pmn-" : "verb",
"t-sa-pmv-" : "verb",
"t-sp-afa-" : "verb",
"t-sp-afd-" : "verb",
"t-sp-afg-" : "verb",
"t-sp-afn-" : "verb",
"t-sp-afv-" : "verb",
"t-sp-amn-" : "verb",
"t-sp-amv-" : "verb",
"t-sp-ana-" : "verb",
"t-sp-ann-" : "verb",
"t-sp-anv-" : "verb",
"v2dpsa---" : "verb",
"t-sa-ana-" : "verb",
"t-sa-ann-" : "verb",
"t-sa-anv-" : "verb",
"t-pp-ama-" : "verb",
"t-sf-amn-" : "verb",
"t-sf-amv-" : "verb",
"t-sf-ana-" : "verb",
"t-sf-ann-" : "verb",
"t-sf-anv-" : "verb",
"t-pp-amn-" : "verb",
"t-pp-amv-" : "verb",
"t-pp-emn-" : "verb",
"t-pp-emv-" : "verb",
"t-sp-efn-" : "verb",
"t-sp-efv-" : "verb",
"t-sp-emg-" : "verb",
"t-sp-emn-" : "verb",
"t-sp-eng-" : "verb",
"t-pf-mmn-" : "verb",
"t-pf-mmv-" : "verb",
"v2plie---" : "verb",
"v2ppse---" : "verb",
"v2prme---" : "verb",
"t-dp-efa-" : "verb",
"t-dp-efn-" : "verb",
"t-dp-efv-" : "verb",
"t-pp-efn-" : "verb",
"t-pp-efv-" : "verb",
"t-pp-ema-" : "verb",
"t-pp-ena-" : "verb",
"t-pp-enn-" : "verb",
"t-pp-env-" : "verb",
"t-sp-efa-" : "verb",
"t-sp-efd-" : "verb",
"t-sp-emd-" : "verb",
"t-sp-end-" : "verb",
"t-da-mma-" : "verb",
"t-da-mmn-" : "verb",
"t-da-mmv-" : "verb",
"t-da-mna-" : "verb",
"t-da-mnn-" : "verb",
"t-da-mnv-" : "verb",
"t-da-pma-" : "verb",
"t-da-pmn-" : "verb",
"t-da-pmv-" : "verb",
"t-da-pna-" : "verb",
"t-da-pnn-" : "verb",
"t-da-pnv-" : "verb",
"t-pa-mmn-" : "verb",
"t-pa-mmv-" : "verb",
"t-pa-pma-" : "verb",
"t-pa-pmn-" : "verb",
"t-pa-pmv-" : "verb",
"t-pa-pna-" : "verb",
"t-pa-pnn-" : "verb",
"t-pa-pnv-" : "verb",
"t-pp-efg-" : "verb",
"t-pp-emg-" : "verb",
"t-pp-eng-" : "verb",
"t-sa-mfn-" : "verb",
"t-sa-mfv-" : "verb",
"t-sa-mma-" : "verb",
"t-sa-mmg-" : "verb",
"t-sa-mmn-" : "verb",
"t-sa-mna-" : "verb",
"t-sa-mng-" : "verb",
"t-sa-mnn-" : "verb",
"t-sa-mnv-" : "verb",
"t-sa-pma-" : "verb",
"t-sa-pmd-" : "verb",
"t-sa-pna-" : "verb",
"t-sa-pnd-" : "verb",
"t-sa-pnn-" : "verb",
"t-sa-pnv-" : "verb",
"t-sp-ema-" : "verb",
"t-sp-ena-" : "verb",
"t-sp-enn-" : "verb",
"t-sp-env-" : "verb",
"t-da-afa-" : "verb",
"t-da-afn-" : "verb",
"t-da-afv-" : "verb",
"t-dp-ama-" : "verb",
"t-dp-amn-" : "verb",
"t-dp-amv-" : "verb",
"t-dp-ana-" : "verb",
"t-dp-ann-" : "verb",
"t-dp-anv-" : "verb",
"t-pa-ama-" : "verb",
"t-pa-amg-" : "verb",
"t-pa-amn-" : "verb",
"t-pa-amv-" : "verb",
"t-pa-ana-" : "verb",
"t-pa-ang-" : "verb",
"t-pa-ann-" : "verb",
"t-pa-anv-" : "verb",
"t-pf-ama-" : "verb",
"t-pp-amg-" : "verb",
"t-pp-ana-" : "verb",
"t-pp-ang-" : "verb",
"t-pp-ann-" : "verb",
"t-pp-anv-" : "verb",
"t-pr-ama-" : "verb",
"t-sa-afn-" : "verb",
"t-sa-afv-" : "verb",
"t-sa-ama-" : "verb",
"t-sa-amd-" : "verb",
"t-sa-amg-" : "verb",
"t-sa-amn-" : "verb",
"t-sa-amv-" : "verb",
"t-sa-and-" : "verb",
"t-sa-ang-" : "verb",
"t-sp-ama-" : "verb",
"t-sp-amg-" : "verb",
"t-sp-ang-" : "verb",
"v-ptiama-" : "verb",
"v2ptia---" : "verb",
"v3pama---" : "verb",
"v3stia---" : "verb",
"t-df-afa-" : "verb",
"t-df-afn-" : "verb",
"t-df-afv-" : "verb",
"t-df-mfa-" : "verb",
"t-df-mfn-" : "verb",
"t-df-mfv-" : "verb",
"t-pf-afg-" : "verb",
"t-pf-afn-" : "verb",
"t-pf-afv-" : "verb",
"t-pf-amd-" : "verb",
"t-pf-amg-" : "verb",
"t-pf-amn-" : "verb",
"t-pf-amv-" : "verb",
"t-pf-ana-" : "verb",
"t-pf-and-" : "verb",
"t-pf-ang-" : "verb",
"t-pf-ann-" : "verb",
"t-pf-anv-" : "verb",
"t-pf-mfd-" : "verb",
"t-pf-mfg-" : "verb",
"t-pf-mfn-" : "verb",
"t-pf-mfv-" : "verb",
"t-pf-mma-" : "verb",
"t-pf-mmg-" : "verb",
"t-pf-mna-" : "verb",
"t-pf-mng-" : "verb",
"t-pf-mnn-" : "verb",
"t-pf-mnv-" : "verb",
"t-sf-afa-" : "verb",
"t-sf-afd-" : "verb",
"t-sf-afn-" : "verb",
"t-sf-afv-" : "verb",
"t-sf-ama-" : "verb",
"t-sf-amd-" : "verb",
"t-sf-and-" : "verb",
"t-sf-mfa-" : "verb",
"t-sf-mfd-" : "verb",
"t-sf-mfg-" : "verb",
"t-sf-mfn-" : "verb",
"t-sf-mfv-" : "verb",
"t-sf-mma-" : "verb",
"t-sf-mmd-" : "verb",
"t-sf-mmn-" : "verb",
"t-sf-mna-" : "verb",
"t-sf-mnd-" : "verb",
"t-sf-mnn-" : "verb",
"t-sf-mnv-" : "verb",
"t-sp-amd-" : "verb",
"t-sp-and-" : "verb",
"v1pfoa---" : "verb",
"v1sfoa---" : "verb",
"v3pfoa---" : "verb",
"t-pp-efd-" : "verb",
"t-pr-amd-" : "verb",
"t-pr-amg-" : "verb",
"t-pr-amn-" : "verb",
"t-pr-amv-" : "verb",
"t-pr-and-" : "verb",
"t-pr-ang-" : "verb",
"t-pr-emd-" : "verb",
"t-pr-emn-" : "verb",
"t-pr-emv-" : "verb",
"t-pr-end-" : "verb",
"t-sp-efg-" : "verb",
"t-sr-amn-" : "verb",
"t-sr-amv-" : "verb",
"t-sr-efa-" : "verb",
"t-sr-efn-" : "verb",
"t-sr-efv-" : "verb",
"t-sr-ema-" : "verb",
"t-sr-emd-" : "verb",
"t-sr-ena-" : "verb",
"t-sr-end-" : "verb",
"t-sr-enn-" : "verb",
"t-sr-env-" : "verb",
"v-ptiamd-" : "verb",
"v-ptiand-" : "verb",
"v-stiamn-" : "verb",
"v1ptia---" : "verb",
"v1stia---" : "verb",
"v2stia---" : "verb",
"v2stim---" : "verb",
"v3ptia---" : "verb",
"t-da-ama-" : "verb",
"t-da-amn-" : "verb",
"t-da-amv-" : "verb",
"t-da-ana-" : "verb",
"t-da-ann-" : "verb",
"t-da-anv-" : "verb",
"t-da-mfa-" : "verb",
"t-da-mfn-" : "verb",
"t-da-mfv-" : "verb",
"t-da-pfa-" : "verb",
"t-da-pfn-" : "verb",
"t-da-pfv-" : "verb",
"t-dr-efa-" : "verb",
"t-dr-efn-" : "verb",
"t-dr-efv-" : "verb",
"t-pa-afn-" : "verb",
"t-pa-afv-" : "verb",
"t-pa-amd-" : "verb",
"t-pa-and-" : "verb",
"t-pa-mfg-" : "verb",
"t-pa-mmd-" : "verb",
"t-pa-mmg-" : "verb",
"t-pa-mna-" : "verb",
"t-pa-mnd-" : "verb",
"t-pa-mng-" : "verb",
"t-pa-mnn-" : "verb",
"t-pa-mnv-" : "verb",
"t-pp-emd-" : "verb",
"t-pp-end-" : "verb",
"t-pr-efg-" : "verb",
"t-pr-emg-" : "verb",
"t-pr-ena-" : "verb",
"t-pr-eng-" : "verb",
"t-pr-enn-" : "verb",
"t-pr-env-" : "verb",
"t-sa-afd-" : "verb",
"t-sa-pfg-" : "verb",
"t-sa-pfn-" : "verb",
"t-sa-pfv-" : "verb",
"t-sa-pmg-" : "verb",
"t-sa-png-" : "verb",
"t-sr-emn-" : "verb",
"v2sfoa---" : "verb",
"t-pa-mfd-" : "verb",
"t-pa-mfn-" : "verb",
"t-pa-mfv-" : "verb",
"t-sa-mfd-" : "verb",
"t-sa-mfg-" : "verb",
"t-sr-efg-" : "verb",
"t-pa-pmg-" : "verb",
"t-pa-png-" : "verb",
"t-dr-pfa-" : "verb",
"t-dr-pfn-" : "verb",
"t-dr-pfv-" : "verb",
"t-pr-pma-" : "verb",
"t-pr-pna-" : "verb",
"t-pr-pnn-" : "verb",
"t-pr-pnv-" : "verb",
"t-sr-pfn-" : "verb",
"t-sr-pfv-" : "verb",
"t-sr-pmn-" : "verb",
"v1spip---" : "verb",
"v2spmp---" : "verb",
"t-pr-ema-" : "verb",
"t-sr-ana-" : "verb",
"t-sr-ann-" : "verb",
"t-sr-anv-" : "verb",
"t-pa-pmd-" : "verb",
"t-pa-pnd-" : "verb",
"t-pf-pfg-" : "verb",
"t-pf-pmg-" : "verb",
"t-pf-png-" : "verb",
"t-sa-pfd-" : "verb",
"t-pp-afd-" : "verb",
"t-pp-efa-" : "verb",
"v--tne---" : "verb",
"t-df-ama-" : "verb",
"t-df-amn-" : "verb",
"t-df-amv-" : "verb",
"t-df-ana-" : "verb",
"t-df-ann-" : "verb",
"t-df-anv-" : "verb",
"v2daip---" : "verb",
"v2dasp---" : "verb",
"v2pamp---" : "verb",
"v3dasp---" : "verb",
"v3pfom---" : "verb",
"t-pa-pfg-" : "verb",
"t-pf-afa-" : "verb",
"t-sa-pfa-" : "verb",
"t-sf-afg-" : "verb",
"v--pnm---" : "verb",
"v--rnm---" : "verb",
"v1spim---" : "verb",
"v2piim---" : "verb",
"v2ppim---" : "verb",
"v2ppmm---" : "verb",
"v2siim---" : "verb",
"v2spim---" : "verb",
"v2spmm---" : "verb",
"v2spsm---" : "verb",
"v3diim---" : "verb",
"v3piim---" : "verb",
"v3siim---" : "verb",
"v3spim---" : "verb",
"v3spom---" : "verb",
"v3spsm---" : "verb",
"v3srim---" : "verb",
"v-stiamv-" : "verb",
"v-stiana-" : "verb",
"v-stiann-" : "verb",
"v-stianv-" : "verb",
"t-pa-efg-" : "verb",
"t-pa-ema-" : "verb",
"t-pa-emd-" : "verb",
"t-pa-emg-" : "verb",
"t-pa-emn-" : "verb",
"t-pa-emv-" : "verb",
"t-pa-end-" : "verb",
"t-pa-eng-" : "verb",
"t-pf-ema-" : "verb",
"t-pf-emn-" : "verb",
"t-pf-emv-" : "verb",
"t-pr-efn-" : "verb",
"t-pr-efv-" : "verb",
"t-sa-efa-" : "verb",
"t-sa-efg-" : "verb",
"t-sa-ema-" : "verb",
"t-sa-emd-" : "verb",
"t-sa-emg-" : "verb",
"t-sa-emn-" : "verb",
"t-sa-ena-" : "verb",
"t-sa-end-" : "verb",
"t-sa-eng-" : "verb",
"t-sa-enn-" : "verb",
"t-sa-env-" : "verb",
"t-sf-ema-" : "verb",
"t-sf-emg-" : "verb",
"t-sf-emn-" : "verb",
"t-sf-ena-" : "verb",
"t-sf-eng-" : "verb",
"t-sf-enn-" : "verb",
"t-sf-env-" : "verb",
"t-sr-efd-" : "verb",
"v1paie---" : "verb",
"v1pfie---" : "verb",
"v2paie---" : "verb",
"t-dp-ema-" : "verb",
"t-dp-emn-" : "verb",
"t-dp-emv-" : "verb",
"t-dp-ena-" : "verb",
"t-dp-enn-" : "verb",
"t-dp-env-" : "verb",
"t-pa-afg-" : "verb",
"t-pa-pfa-" : "verb",
"t-pa-pfn-" : "verb",
"t-pa-pfv-" : "verb",
"t-sa-afa-" : "verb",
"t-sa-afg-" : "verb",
"t-sa-mmd-" : "verb",
"t-sa-mnd-" : "verb",
"v2pfip---" : "verb",
"v3dase---" : "verb",
"v3prme---" : "verb",
"v3srme---" : "verb",
"t-dr-afa-" : "verb",
"t-dr-afn-" : "verb",
"t-dr-afv-" : "verb",
"t-dr-ama-" : "verb",
"t-dr-amn-" : "verb",
"t-dr-amv-" : "verb",
"t-dr-ana-" : "verb",
"t-dr-ann-" : "verb",
"t-dr-anv-" : "verb",
"t-pf-mmd-" : "verb",
"t-pf-mnd-" : "verb",
"t-pr-afg-" : "verb",
"t-pr-ana-" : "verb",
"t-pr-ann-" : "verb",
"t-pr-anv-" : "verb",
"t-pr-efd-" : "verb",
"t-pt-emd-" : "verb",
"t-pt-end-" : "verb",
"t-sp-pmn-" : "verb",
"t-sr-afa-" : "verb",
"t-sr-afn-" : "verb",
"t-sr-afv-" : "verb",
"t-sr-ama-" : "verb",
"t-sr-amd-" : "verb",
"t-sr-amg-" : "verb",
"t-sr-and-" : "verb",
"t-sr-ang-" : "verb",
"t-sr-emg-" : "verb",
"t-sr-eng-" : "verb",
"t-st-ema-" : "verb",
"t-st-ena-" : "verb",
"t-st-enn-" : "verb",
"t-st-env-" : "verb",
"v-ptiafg-" : "verb",
"v-ptiamg-" : "verb",
"v-ptiamn-" : "verb",
"v-ptiamv-" : "verb",
"v-ptiang-" : "verb",
"v-stiafa-" : "verb",
"v3ptie---" : "verb",
"t-sp-mma-" : "verb",
"t-sp-mna-" : "verb",
"t-sp-mnn-" : "verb",
"t-sp-mnv-" : "verb",
"t-sr-mma-" : "verb",
"t-sr-mna-" : "verb",
"t-sr-mnn-" : "verb",
"t-sr-mnv-" : "verb",
"t-pa-afa-" : "verb",
"t-pa-mma-" : "verb",
"v1sfom---" : "verb",
"v2pfom---" : "verb",
"v2sfom---" : "verb",
"v3sfom---" : "verb",
"t-pr-efa-" : "verb",
"v3pfip---" : "verb",
"t-sf-amg-" : "verb",
"t-sf-ang-" : "verb",
"t-sa-mfa-" : "verb",
"v3dasa---" : "verb",
"t-dr-ema-" : "verb",
"t-dr-emn-" : "verb",
"t-dr-emv-" : "verb",
"t-dr-ena-" : "verb",
"t-dr-enn-" : "verb",
"t-dr-env-" : "verb",
"v2dpoa---" : "verb",
"t-pa-ena-" : "verb",
"t-pa-enn-" : "verb",
"t-pa-env-" : "verb",
"t-pp-mfn-" : "verb",
"t-pp-mfv-" : "verb",
"t-pp-mma-" : "verb",
"t-pp-mmn-" : "verb",
"t-pp-mmv-" : "verb",
"t-sp-mfa-" : "verb",
"t-sp-mfd-" : "verb",
"t-sp-mfn-" : "verb",
"t-sp-mfv-" : "verb",
"t-sp-mmd-" : "verb",
"t-sp-mmn-" : "verb",
"t-sp-mnd-" : "verb",
"v1piim---" : "verb",
"v1ppim---" : "verb",
"v1siim---" : "verb",
"t-pa-pfd-" : "verb",
"v2pfoa---" : "verb",
"v3damm---" : "verb",
"t-sf-pma-" : "verb",
"t-sf-pna-" : "verb",
"t-sf-pnn-" : "verb",
"t-sf-pnv-" : "verb",
"t-dp-mfa-" : "verb",
"t-dp-mfn-" : "verb",
"t-dp-mfv-" : "verb",
"t-pp-mfg-" : "verb",
"t-pp-mmd-" : "verb",
"t-pp-mmg-" : "verb",
"t-pp-mna-" : "verb",
"t-pp-mnd-" : "verb",
"t-pp-mng-" : "verb",
"t-pp-mnn-" : "verb",
"t-pp-mnv-" : "verb",
"t-pr-mfg-" : "verb",
"t-pr-mma-" : "verb",
"t-pr-mmd-" : "verb",
"t-pr-mmg-" : "verb",
"t-pr-mmn-" : "verb",
"t-pr-mmv-" : "verb",
"t-pr-mnd-" : "verb",
"t-pr-mng-" : "verb",
"t-sp-mmg-" : "verb",
"t-sp-mng-" : "verb",
"t-sr-mmg-" : "verb",
"t-sr-mmn-" : "verb",
"t-sr-mng-" : "verb",
"v1plim---" : "verb",
"v1ppom---" : "verb",
"v1ppsm---" : "verb",
"v1prim---" : "verb",
"v1spsm---" : "verb",
"v1srim---" : "verb",
"v2plim---" : "verb",
"v2ppsm---" : "verb",
"v2prim---" : "verb",
"v2prmm---" : "verb",
"v2spom---" : "verb",
"v2srim---" : "verb",
"v3ppim---" : "verb",
"v3ppom---" : "verb",
"v3ppsm---" : "verb",
"v3prim---" : "verb",
"t-pp-pmn-" : "verb",
"t-pp-pmv-" : "verb",
"v2plip---" : "verb",
"v2prip---" : "verb",
"t-sa-efn-" : "verb",
"t-sa-efv-" : "verb",
"t-sa-emv-" : "verb",
"v1paoe---" : "verb",
"v3same---" : "verb",
"t-sf-mmg-" : "verb",
"t-sf-mng-" : "verb",
"v-stiamg-" : "verb",
"v-stiang-" : "verb",
"v3stoa---" : "verb",
"v2diim---" : "verb",
"v2dpim---" : "verb",
"v2dpmm---" : "verb",
"v3dpim---" : "verb",
"t-sf-pmg-" : "verb",
"t-sf-png-" : "verb",
"v2pfie---" : "verb",
"t-st-emg-" : "verb",
"t-st-emn-" : "verb",
"t-st-eng-" : "verb",
"t-pf-mfa-" : "verb",
"v1spom---" : "verb",
"v2srmm---" : "verb",
"t-sr-mfn-" : "verb",
"t-sr-mfv-" : "verb",
"t-sp-mfg-" : "verb",
"v3spmm---" : "verb",
"v3dpoa---" : "verb",
"t-pa-afd-" : "verb",
"t-pr-afa-" : "verb",
"t-pr-afd-" : "verb",
"t-pr-afn-" : "verb",
"t-pr-afv-" : "verb",
"t-sr-afd-" : "verb",
"t-sr-afg-" : "verb",
"v1pfip---" : "verb",
"v2dtia---" : "verb",
"v3dtia---" : "verb",
"t-sr-emv-" : "verb",
"v-ptiana-" : "verb",
"v-ptiann-" : "verb",
"v-ptianv-" : "verb",
"v-stiama-" : "verb",
"v2dpie---" : "verb",
"t-sp-emv-" : "verb",
"v--tnm---" : "verb",
"v2ptim---" : "verb",
"v2dfie---" : "verb",
"v2dtie---" : "verb",
"v3dfie---" : "verb",
"v3dtie---" : "verb",
"v3dama---" : "verb",
"t-pf-pmn-" : "verb",
"t-pf-pmv-" : "verb",
"t-sf-pmd-" : "verb",
"t-sf-pnd-" : "verb",
"t-da-pmd-" : "verb",
"t-da-pmg-" : "verb",
"t-da-pnd-" : "verb",
"t-da-png-" : "verb",
"t-pf-pfa-" : "verb",
"t-pt-efn-" : "verb",
"t-pt-efv-" : "verb",
"t-pt-ema-" : "verb",
"t-sf-pfg-" : "verb",
"t-st-efd-" : "verb",
"t-pf-efn-" : "verb",
"t-pf-efv-" : "verb",
"t-sf-efd-" : "verb",
"v2paoe---" : "verb",
"t-pt-emn-" : "verb",
"t-pt-emv-" : "verb",
"t-pa-mfa-" : "verb",
"t-pf-pma-" : "verb",
"t-sf-pmn-" : "verb",
"t-pf-afd-" : "verb",
"v3pamp---" : "verb",
"t-sp-pmd-" : "verb",
"t-sp-pnd-" : "verb",
"v-ptiafn-" : "verb",
"v-ptiafv-" : "verb",
"v-stiafd-" : "verb",
"v-stiafn-" : "verb",
"v-stiafv-" : "verb",
"v3stoe---" : "verb",
"t-sf-pfa-" : "verb",
"v3p------" : "verb",
"t-df-pfa-" : "verb",
"t-df-pfn-" : "verb",
"t-df-pfv-" : "verb",
"t-pf-pna-" : "verb",
"t-pf-pnn-" : "verb",
"t-pf-pnv-" : "verb",
"t-sf-pfn-" : "verb",
"t-sf-pfv-" : "verb",
"v2daim---" : "verb",
"v2damm---" : "verb",
"t-da-ema-" : "verb",
"t-da-emn-" : "verb",
"t-da-emv-" : "verb",
"t-da-ena-" : "verb",
"t-da-enn-" : "verb",
"t-da-env-" : "verb",
"t-dp-mma-" : "verb",
"t-dp-mmn-" : "verb",
"t-dp-mmv-" : "verb",
"t-dp-mna-" : "verb",
"t-dp-mnn-" : "verb",
"t-dp-mnv-" : "verb",
"t-sa-mmv-" : "verb",
"v2daoa---" : "verb",
"t-dp-emd-" : "verb",
"t-dp-emg-" : "verb",
"t-dp-end-" : "verb",
"t-dp-eng-" : "verb",
"t-dr-emd-" : "verb",
"t-dr-emg-" : "verb",
"t-dr-end-" : "verb",
"t-dr-eng-" : "verb",
"t-dp-amd-" : "verb",
"t-dp-amg-" : "verb",
"t-dp-and-" : "verb",
"t-dp-ang-" : "verb",
"t-sp--na-" : "verb",
"t-sp--nn-" : "verb",
"t-sp--nv-" : "verb",
"v2s-sa---" : "verb",
"v3s-sa---" : "verb",
"v2dlia---" : "verb",
"v2plia---" : "verb",
"v2dam----" : "verb",
"v2ptie---" : "verb",
"t-da-efa-" : "verb",
"t-da-efn-" : "verb",
"t-da-efv-" : "verb",
"t-pr-mfn-" : "verb",
"t-pr-mfv-" : "verb",
"t-sr-mfd-" : "verb",
"t-sp-pfn-" : "verb",
"t-sp-pfv-" : "verb",
"v3sfop---" : "verb",
"t--r-----" : "verb",
"t-da-amd-" : "verb",
"t-da-amg-" : "verb",
"t-da-and-" : "verb",
"t-da-ang-" : "verb",
"v3ptim---" : "verb",
"t-sf-mmv-" : "verb",
"v3proa---" : "verb",
"t-pf-emd-" : "verb",
"t-pf-end-" : "verb",
"t-sf-efa-" : "verb",
"t-sf-emd-" : "verb",
"t-sf-end-" : "verb",
"t-st-efa-" : "verb",
"t-st-emd-" : "verb",
"t-st-end-" : "verb",
"t-da-pfd-" : "verb",
"t-da-pfg-" : "verb",
"v3sfoe---" : "verb",
"v1stoa---" : "verb",
"v3pfop---" : "verb",
"v3s------" : "verb",
"t-pr-pfg-" : "verb",
"t-pr-pmd-" : "verb",
"t-pr-pmg-" : "verb",
"t-pr-pmn-" : "verb",
"t-pr-pmv-" : "verb",
"t-pr-pnd-" : "verb",
"t-pr-png-" : "verb",
"v3ptoe---" : "verb",
"v2dpoe---" : "verb",
"t-pf-pmd-" : "verb",
"t-pf-pnd-" : "verb",
"v1siip---" : "verb",
"v1srip---" : "verb",
"v2piip---" : "verb",
"v2ppip---" : "verb",
"v2ppmp---" : "verb",
"v2ppsp---" : "verb",
"v2spip---" : "verb",
"v2spsp---" : "verb",
"v3spsp---" : "verb",
"t-pp-pma-" : "verb",
"v1piip---" : "verb",
"v1ppsp---" : "verb",
"v1spsp---" : "verb",
"t-pp-mfa-" : "verb",
"v2ppom---" : "verb",
"t-st-efn-" : "verb",
"t-st-efv-" : "verb",
"v3prsa---" : "verb",
"t-pt-mma-" : "verb",
"v3ppmm---" : "verb",
"v2dlie---" : "verb",
"v2drie---" : "verb",
"v3drie---" : "verb",
"t-dp-pma-" : "verb",
"t-dp-pmn-" : "verb",
"t-dp-pmv-" : "verb",
"t-dp-pna-" : "verb",
"t-dp-pnn-" : "verb",
"t-dp-pnv-" : "verb",
"t-dr-pma-" : "verb",
"t-dr-pmn-" : "verb",
"t-dr-pmv-" : "verb",
"t-dr-pna-" : "verb",
"t-dr-pnn-" : "verb",
"t-dr-pnv-" : "verb",
"t-pp-pfn-" : "verb",
"t-pp-pfv-" : "verb",
"t-pp-pmd-" : "verb",
"t-pp-pnd-" : "verb",
"t-pr-pfn-" : "verb",
"t-pr-pfv-" : "verb",
"t-sp-pfa-" : "verb",
"t-sp-pfd-" : "verb",
"t-sp-pfg-" : "verb",
"t-sp-pma-" : "verb",
"t-sp-pmg-" : "verb",
"t-sp-pna-" : "verb",
"t-sp-png-" : "verb",
"t-sp-pnn-" : "verb",
"t-sp-pnv-" : "verb",
"t-sr-pfa-" : "verb",
"t-sr-pfd-" : "verb",
"t-sr-pfg-" : "verb",
"t-sr-pma-" : "verb",
"t-sr-pmg-" : "verb",
"t-sr-pna-" : "verb",
"t-sr-png-" : "verb",
"t-sr-pnn-" : "verb",
"t-sr-pnv-" : "verb",
"v2sao----" : "verb",
"t-dr-amd-" : "verb",
"t-dr-amg-" : "verb",
"t-dr-and-" : "verb",
"t-dr-ang-" : "verb",
"t-dr-mfa-" : "verb",
"t-dr-mfn-" : "verb",
"t-dr-mfv-" : "verb",
"t-pr-mna-" : "verb",
"t-pr-mnn-" : "verb",
"t-pr-mnv-" : "verb",
"t-pp-an--" : "verb",
"t-da-mmd-" : "verb",
"t-da-mmg-" : "verb",
"t-da-mnd-" : "verb",
"t-da-mng-" : "verb",
"t-dp-efd-" : "verb",
"t-dp-efg-" : "verb",
"v2dpse---" : "verb",
"v3dpse---" : "verb",
"t-dp-afd-" : "verb",
"t-dp-afg-" : "verb",
"v1sfop---" : "verb",
"v1stip---" : "verb",
"t-dp-pfa-" : "verb",
"t-dp-pfn-" : "verb",
"t-dp-pfv-" : "verb",
"t-pp-pna-" : "verb",
"t-pp-pnn-" : "verb",
"t-pp-pnv-" : "verb",
"t-df-afd-" : "verb",
"t-df-afg-" : "verb",
"t-pp-mfd-" : "verb",
"t-pa-efa-" : "verb",
"v1stoe---" : "verb",
"v2prse---" : "verb",
"t-pa-efn-" : "verb",
"t-pa-efv-" : "verb",
"t-sa-efd-" : "verb",
"t-df-efa-" : "verb",
"t-df-efn-" : "verb",
"t-df-efv-" : "verb",
"t-pf-ena-" : "verb",
"t-pf-enn-" : "verb",
"t-pf-env-" : "verb",
"t-sf-efn-" : "verb",
"t-sf-efv-" : "verb",
"v2sfoe---" : "verb",
"v3srse---" : "verb",
"v3dam----" : "verb",
"v3pame---" : "verb",
"t-pf-pfn-" : "verb",
"t-pf-pfv-" : "verb",
"t-sf-pfd-" : "verb",
"t-sf-pmv-" : "verb",
"t-pf-pfd-" : "verb",
"v2dasm---" : "verb",
"v3dasm---" : "verb",
"v3dpoe---" : "verb",
"t-st-mmn-" : "verb",
"v1ptim---" : "verb",
"v3daop---" : "verb",
"v2dpsm---" : "verb",
"v3dpsm---" : "verb",
"t-pt-mmn-" : "verb",
"t-pt-mmv-" : "verb",
"v2ppop---" : "verb",
"t-pf-efg-" : "verb",
"t-pf-emg-" : "verb",
"t-pf-eng-" : "verb",
"t-df-mma-" : "verb",
"t-df-mmn-" : "verb",
"t-df-mmv-" : "verb",
"t-df-mna-" : "verb",
"t-df-mnn-" : "verb",
"t-df-mnv-" : "verb",
"v1plip---" : "verb",
"v1prip---" : "verb",
"v1slip---" : "verb",
"v2dlip---" : "verb",
"v2drip---" : "verb",
"v2slip---" : "verb",
"v2srip---" : "verb",
"v2srmp---" : "verb",
"v3dlip---" : "verb",
"v3drip---" : "verb",
"v3srmp---" : "verb",
"v--pia---" : "verb",
"v1proa---" : "verb",
"v2drsa---" : "verb",
"v3drma---" : "verb",
"v3drsa---" : "verb",
"t-sr-pmv-" : "verb",
"t-pr-mfa-" : "verb",
"t-sr-mfg-" : "verb",
"t-pf-efa-" : "verb",
"t-sf-efg-" : "verb",
"v1p------" : "verb",
"t-pp-pfg-" : "verb",
"t-pp-pmg-" : "verb",
"t-pp-png-" : "verb",
"v2spop---" : "verb",
"v2sa-m---" : "verb",
"t-st-mmg-" : "verb",
"t-st-mng-" : "verb",
"v3daom---" : "verb",
"t-pt-mfg-" : "verb",
"t-pt-mmg-" : "verb",
"t-pt-mng-" : "verb",
"t-st-mma-" : "verb",
"t-st-mna-" : "verb",
"t-st-mnn-" : "verb",
"t-st-mnv-" : "verb",
"v3dpmm---" : "verb",
"v3dpom---" : "verb",
"v3ptom---" : "verb",
"v3stom---" : "verb",
"t-dr-mma-" : "verb",
"t-dr-mmn-" : "verb",
"t-dr-mmv-" : "verb",
"t-dr-mna-" : "verb",
"t-dr-mnn-" : "verb",
"t-dr-mnv-" : "verb",
"t-sr-mfa-" : "verb",
"t-sr-mmd-" : "verb",
"t-sr-mnd-" : "verb",
"v2dlim---" : "verb",
"v2drim---" : "verb",
"v3drim---" : "verb",
"v2dpom---" : "verb",
"t-da-afd-" : "verb",
"t-da-afg-" : "verb",
"v3prma---" : "verb",
"v2sroe---" : "verb",
"v3sroe---" : "verb",
"t-pa-efd-" : "verb",
"v3daie---" : "verb",
"v3pfoe---" : "verb",
"v1drie---" : "verb",
"v2daie---" : "verb",
"t-dr-afd-" : "verb",
"t-dr-afg-" : "verb",
"v1pfop---" : "verb",
"v1ptom---" : "verb",
"v1stom---" : "verb",
"v2daop---" : "verb",
"v2dfip---" : "verb",
"v2dtim---" : "verb",
"v2pfop---" : "verb",
"v2ptom---" : "verb",
"v2sfop---" : "verb",
"v2stom---" : "verb",
"v3dfip---" : "verb",
"v3dtim---" : "verb",
"v3ppsp---" : "verb",
"t-sf-emv-" : "verb",
"v1srse---" : "verb",
"v--pme---" : "verb",
"v1sfoe---" : "verb",
"v2droa---" : "verb",
"v3droa---" : "verb",
"v1dpie---" : "verb",
"v1dpsa---" : "verb",
"t-dt-efa-" : "verb",
"t-dt-efn-" : "verb",
"t-dt-efv-" : "verb",
"t-pt-ena-" : "verb",
"t-pt-enn-" : "verb",
"t-pt-env-" : "verb",
"v1dasa---" : "verb",
"t-sp-mmv-" : "verb",
"t-pp-pfa-" : "verb",
"t-sr-pmd-" : "verb",
"t-sr-pnd-" : "verb",
"v2p------" : "verb",
"v1ppop---" : "verb",
"v1spop---" : "verb",
"v3diip---" : "verb",
"v3ppop---" : "verb",
"v1pfoe---" : "verb",
"v2daom---" : "verb",
"t-pt-efa-" : "verb",
"t-st-efg-" : "verb",
"v2stip---" : "verb",
"v1p-sa---" : "verb",
"v2d-sa---" : "verb",
"v2p-sa---" : "verb",
"v3d-sa---" : "verb",
"v3p-sa---" : "verb",
"x-----n--" : "x",
"x-s----g-" : "x",
"x-s----n-" : "x",
"x-s---fd-" : "x",
"x-s---n--" : "x",
"x-s---na-" : "x",
"x-s---nn-" : "x",
"x-s---nv-" : "x",
"x-s---mv-" : "x",
"x-p------" : "x",
"x-d----a-" : "x",
"x-d----d-" : "x",
"x-d----g-" : "x",
"x-d----n-" : "x",
"x-d----v-" : "x",
"x-p----g-" : "x",
"x-p---fa-" : "x",
"x-p---fn-" : "x",
"x-p---fv-" : "x",
"x-p---ma-" : "x",
"x-p---mn-" : "x",
"x-p---mv-" : "x",
"x-p---na-" : "x",
"x-p---nv-" : "x",
"x-s----d-" : "x",
"x-s---fa-" : "x",
"x-s---fn-" : "x",
"x-s---ma-" : "x",
"x-s---mn-" : "x",  # up to here added after curation
"---------" : "x",
"--p---fa-" : "x",
"--s---ma-" : "x",
"-3paia---" : "x",
"-3paim---" : "x",
"-3siia---" : "x",
"a--------" : "adj",
"a-------s" : "adj",
"a-d---fa-" : "adj",
"a-d---fd-" : "adj",
"a-d---fg-" : "adj",
"a-d---fn-" : "adj",
"a-d---ma-" : "adj",
"a-d---md-" : "adj",
"a-d---mg-" : "adj",
"a-d---mn-" : "adj",
"a-d---mnc" : "adj",
"a-d---mv-" : "adj",
"a-d---na-" : "adj",
"a-d---ng-" : "adj",
"a-d---nn-" : "adj",
"a-p----dc" : "adj",
"a-p---fa-" : "adj",
"a-p---fac" : "adj",
"a-p---fas" : "adj",
"a-p---fd-" : "adj",
"a-p---fdc" : "adj",
"a-p---fds" : "adj",
"a-p---fg-" : "adj",
"a-p---fgc" : "adj",
"a-p---fn-" : "adj",
"a-p---fnc" : "adj",
"a-p---fns" : "adj",
"a-p---fv-" : "adj",
"a-p---m--" : "adj",
"a-p---m-c" : "adj",
"a-p---ma-" : "adj",
"a-p---mac" : "adj",
"a-p---mas" : "adj",
"a-p---md-" : "adj",
"a-p---mdc" : "adj",
"a-p---mds" : "adj",
"a-p---mg-" : "adj",
"a-p---mgc" : "adj",
"a-p---mgs" : "adj",
"a-p---mn-" : "adj",
"a-p---mnc" : "adj",
"a-p---mns" : "adj",
"a-p---mv-" : "adj",
"a-p---mvs" : "adj",
"a-p---na-" : "adj",
"a-p---nac" : "adj",
"a-p---nas" : "adj",
"a-p---nd-" : "adj",
"a-p---ndc" : "adj",
"a-p---nds" : "adj",
"a-p---ng-" : "adj",
"a-p---ngs" : "adj",
"a-p---nn-" : "adj",
"a-p---nnc" : "adj",
"a-p---nns" : "adj",
"a-p---nv-" : "adj",
"a-s----d-" : "adj",
"a-s----dc" : "adj",
"a-s----g-" : "adj",
"a-s----gc" : "adj",
"a-s---fa-" : "adj",
"a-s---fac" : "adj",
"a-s---fas" : "adj",
"a-s---fd-" : "adj",
"a-s---fds" : "adj",
"a-s---fg-" : "adj",
"a-s---fgc" : "adj",
"a-s---fgs" : "adj",
"a-s---fn-" : "adj",
"a-s---fnc" : "adj",
"a-s---fns" : "adj",
"a-s---fv-" : "adj",
"a-s---m--" : "adj",
"a-s---ma-" : "adj",
"a-s---mac" : "adj",
"a-s---mas" : "adj",
"a-s---md-" : "adj",
"a-s---mdc" : "adj",
"a-s---mds" : "adj",
"a-s---mg-" : "adj",
"a-s---mgc" : "adj",
"a-s---mgs" : "adj",
"a-s---mn-" : "adj",
"a-s---mnc" : "adj",
"a-s---mns" : "adj",
"a-s---mv-" : "adj",
"a-s---mvc" : "adj",
"a-s---mvs" : "adj",
"a-s---na-" : "adj",
"a-s---nac" : "adj",
"a-s---nas" : "adj",
"a-s---nd-" : "adj",
"a-s---ndc" : "adj",
"a-s---nds" : "adj",
"a-s---ng-" : "adj",
"a-s---nn-" : "adj",
"a-s---nnc" : "adj",
"a-s---nns" : "adj",
"a-s---nv-" : "adj",
"a-s---nvs" : "adj",
"c--------" : "cconj",
"c--------" : "sconj",
"d--------" : "adv",
"d-------c" : "adv",
"d-------s" : "adv",
"g--------" : "part",
"i--------" : "intj",
"l--------" : "det",
"l-d---fa-" : "det",
"l-d---fg-" : "det",
"l-d---mg-" : "det",
"l-d---mn-" : "det",
"l-d---na-" : "det",
"l-d---nn-" : "det",
"l-p---fa-" : "det",
"l-p---fd-" : "det",
"l-p---fg-" : "det",
"l-p---fn-" : "det",
"l-p---ma-" : "det",
"l-p---md-" : "det",
"l-p---mg-" : "det",
"l-p---mn-" : "det",
"l-p---na-" : "det",
"l-p---nd-" : "det",
"l-p---ng-" : "det",
"l-p---nn-" : "det",
"l-s---fa-" : "det",
"l-s---fd-" : "det",
"l-s---fg-" : "det",
"l-s---fn-" : "det",
"l-s---ma-" : "det",
"l-s---md-" : "det",
"l-s---mg-" : "det",
"l-s---mn-" : "det",
"l-s---na-" : "det",
"l-s---nd-" : "det",
"l-s---ng-" : "det",
"l-s---nn-" : "det",
"m--------" : "num",
"m-p---m--" : "num",
"m-p---md-" : "num",
"m-p---nn-" : "num",
"n-----fg-" : "noun",
"n-----na-" : "noun",
"n-----nn-" : "noun",
"n-d----a-" : "noun",
"n-d---fa-" : "noun",
"n-d---fd-" : "noun",
"n-d---fg-" : "noun",
"n-d---fn-" : "noun",
"n-d---ma-" : "noun",
"n-d---md-" : "noun",
"n-d---mg-" : "noun",
"n-d---mn-" : "noun",
"n-d---mv-" : "noun",
"n-d---na-" : "noun",
"n-d---nn-" : "noun",
"n-p----d-" : "noun",
"n-p----g-" : "noun",
"n-p---fa-" : "noun",
"n-p---fd-" : "noun",
"n-p---fg-" : "noun",
"n-p---fn-" : "noun",
"n-p---fv-" : "noun",
"n-p---ma-" : "noun",
"n-p---md-" : "noun",
"n-p---mg-" : "noun",
"n-p---mn-" : "noun",
"n-p---mv-" : "noun",
"n-p---na-" : "noun",
"n-p---nd-" : "noun",
"n-p---ng-" : "noun",
"n-p---nn-" : "noun",
"n-p---nv-" : "noun",
"n-s----d-" : "noun",
"n-s----g-" : "noun",
"n-s----n-" : "noun",
"n-s----v-" : "noun",
"n-s---fa-" : "noun",
"n-s---fd-" : "noun",
"n-s---fg-" : "noun",
"n-s---fn-" : "noun",
"n-s---fv-" : "noun",
"n-s---m--" : "noun",
"n-s---ma-" : "noun",
"n-s---md-" : "noun",
"n-s---mg-" : "noun",
"n-s---mn-" : "noun",
"n-s---mv-" : "noun",
"n-s---na-" : "noun",
"n-s---nd-" : "noun",
"n-s---ng-" : "noun",
"n-s---nn-" : "noun",
"n-s---nv-" : "noun",
"p--------" : "pron",
"p-d----d-" : "pron",
"p-d----n-" : "pron",
"p-d---fa-" : "pron",
"p-d---fd-" : "pron",
"p-d---fg-" : "pron",
"p-d---fn-" : "pron",
"p-d---ma-" : "pron",
"p-d---md-" : "pron",
"p-d---mg-" : "pron",
"p-d---mn-" : "pron",
"p-d---mv-" : "pron",
"p-p----a-" : "pron",
"p-p----d-" : "pron",
"p-p----g-" : "pron",
"p-p----n-" : "pron",
"p-p---fa-" : "pron",
"p-p---fd-" : "pron",
"p-p---fg-" : "pron",
"p-p---fn-" : "pron",
"p-p---ma-" : "pron",
"p-p---md-" : "pron",
"p-p---mg-" : "pron",
"p-p---mn-" : "pron",
"p-p---na-" : "pron",
"p-p---nd-" : "pron",
"p-p---ng-" : "pron",
"p-p---nn-" : "pron",
"p-s----a-" : "pron",
"p-s----d-" : "pron",
"p-s----g-" : "pron",
"p-s----n-" : "pron",
"p-s---fa-" : "pron",
"p-s---fd-" : "pron",
"p-s---fg-" : "pron",
"p-s---fn-" : "pron",
"p-s---ma-" : "pron",
"p-s---md-" : "pron",
"p-s---mg-" : "pron",
"p-s---mn-" : "pron",
"p-s---mv-" : "pron",
"p-s---na-" : "pron",
"p-s---nd-" : "pron",
"p-s---ng-" : "pron",
"p-s---nn-" : "pron",
"p1p---fa-" : "pron",
"p1p---ma-" : "pron",
"p1p---md-" : "pron",
"p1p---mg-" : "pron",
"p1p---mn-" : "pron",
"p1s---fa-" : "pron",
"p1s---fd-" : "pron",
"p1s---fg-" : "pron",
"p1s---fn-" : "pron",
"p1s---ma-" : "pron",
"p1s---md-" : "pron",
"p1s---mg-" : "pron",
"p1s---mn-" : "pron",
"p2p----a-" : "pron",
"p2p----d-" : "pron",
"p2p---ma-" : "pron",
"p2p---mg-" : "pron",
"p2p---mn-" : "pron",
"p2s----a-" : "pron",
"p2s----d-" : "pron",
"p2s----g-" : "pron",
"p2s----n-" : "pron",
"p2s---ma-" : "pron",
"p2s---md-" : "pron",
"p2s---mg-" : "pron",
"p3s---fa-" : "pron",
"p3s---ma-" : "pron",
"r--------" : "adp",
"u--------" : "punct",
"v---na---" : "verb",
"v--amm---" : "verb",
"v--an----" : "verb",
"v--ana---" : "verb",
"v--ane---" : "verb",
"v--anm---" : "verb",
"v--anp---" : "verb",
"v--fna---" : "verb",
"v--fne---" : "verb",
"v--fnm---" : "verb",
"v--fnp---" : "verb",
"v--pna---" : "verb",
"v--pnd---" : "verb",
"v--pne---" : "verb",
"v--pnp---" : "verb",
"v--ppefa-" : "verb",
"v--ppemn-" : "verb",
"v--rn----" : "verb",
"v--rna---" : "verb",
"v--rne---" : "verb",
"v--rnp---" : "verb",
"v--tna---" : "verb",
"v-dapafn-" : "verb",
"v-dapama-" : "verb",
"v-dapamg-" : "verb",
"v-dapamn-" : "verb",
"v-dapmfn-" : "verb",
"v-dapmmn-" : "verb",
"v-dappma-" : "verb",
"v-dappmn-" : "verb",
"v-dppafg-" : "verb",
"v-dppama-" : "verb",
"v-dppamn-" : "verb",
"v-dppefn-" : "verb",
"v-dppema-" : "verb",
"v-dppemd-" : "verb",
"v-dppemn-" : "verb",
"v-dpppmn-" : "verb",
"v-drpama-" : "verb",
"v-drpamn-" : "verb",
"v-drpefn-" : "verb",
"v-drpemn-" : "verb",
"v-p-pmma-" : "verb",
"v-pap-mn-" : "verb",
"v-papafa-" : "verb",
"v-papafg-" : "verb",
"v-papafn-" : "verb",
"v-papama-" : "verb",
"v-papamd-" : "verb",
"v-papamg-" : "verb",
"v-papamn-" : "verb",
"v-papana-" : "verb",
"v-papand-" : "verb",
"v-papann-" : "verb",
"v-papefn-" : "verb",
"v-papema-" : "verb",
"v-papemn-" : "verb",
"v-papmfa-" : "verb",
"v-papmfg-" : "verb",
"v-papmfn-" : "verb",
"v-papmma-" : "verb",
"v-papmmd-" : "verb",
"v-papmmg-" : "verb",
"v-papmmn-" : "verb",
"v-papmna-" : "verb",
"v-papmng-" : "verb",
"v-papmnn-" : "verb",
"v-pappfd-" : "verb",
"v-pappfg-" : "verb",
"v-pappfn-" : "verb",
"v-pappma-" : "verb",
"v-pappmd-" : "verb",
"v-pappmg-" : "verb",
"v-pappmn-" : "verb",
"v-pappna-" : "verb",
"v-pappng-" : "verb",
"v-pappnn-" : "verb",
"v-pfpama-" : "verb",
"v-pfpamg-" : "verb",
"v-pfpamn-" : "verb",
"v-pfpema-" : "verb",
"v-pfpemn-" : "verb",
"v-pfpmfa-" : "verb",
"v-pfpmfn-" : "verb",
"v-pfpmma-" : "verb",
"v-pfpmmd-" : "verb",
"v-pfpmmg-" : "verb",
"v-pfpmmn-" : "verb",
"v-pfpmnn-" : "verb",
"v-pfppmn-" : "verb",
"v-ppp-mn-" : "verb",
"v-pppafa-" : "verb",
"v-pppafd-" : "verb",
"v-pppafg-" : "verb",
"v-pppafn-" : "verb",
"v-pppafv-" : "verb",
"v-pppama-" : "verb",
"v-pppamd-" : "verb",
"v-pppamg-" : "verb",
"v-pppamn-" : "verb",
"v-pppamv-" : "verb",
"v-pppana-" : "verb",
"v-pppand-" : "verb",
"v-pppang-" : "verb",
"v-pppann-" : "verb",
"v-pppefa-" : "verb",
"v-pppefd-" : "verb",
"v-pppefg-" : "verb",
"v-pppefn-" : "verb",
"v-pppefv-" : "verb",
"v-pppema-" : "verb",
"v-pppemd-" : "verb",
"v-pppemg-" : "verb",
"v-pppemn-" : "verb",
"v-pppemv-" : "verb",
"v-pppena-" : "verb",
"v-pppend-" : "verb",
"v-pppeng-" : "verb",
"v-pppenn-" : "verb",
"v-ppppma-" : "verb",
"v-ppppmd-" : "verb",
"v-ppppmn-" : "verb",
"v-prp-mn-" : "verb",
"v-prpafa-" : "verb",
"v-prpafd-" : "verb",
"v-prpafn-" : "verb",
"v-prpama-" : "verb",
"v-prpamd-" : "verb",
"v-prpamg-" : "verb",
"v-prpamn-" : "verb",
"v-prpana-" : "verb",
"v-prpang-" : "verb",
"v-prpefa-" : "verb",
"v-prpefd-" : "verb",
"v-prpefg-" : "verb",
"v-prpefn-" : "verb",
"v-prpema-" : "verb",
"v-prpemd-" : "verb",
"v-prpemg-" : "verb",
"v-prpemn-" : "verb",
"v-prpena-" : "verb",
"v-prpend-" : "verb",
"v-prpeng-" : "verb",
"v-prpenn-" : "verb",
"v-prppfn-" : "verb",
"v-prppmn-" : "verb",
"v-sagamn-" : "verb",
"v-saiamn-" : "verb",
"v-samp---" : "verb",
"v-sap-mg-" : "verb",
"v-sap-mn-" : "verb",
"v-sapafa-" : "verb",
"v-sapafd-" : "verb",
"v-sapafg-" : "verb",
"v-sapafn-" : "verb",
"v-sapama-" : "verb",
"v-sapamd-" : "verb",
"v-sapamg-" : "verb",
"v-sapamn-" : "verb",
"v-sapamv-" : "verb",
"v-sapana-" : "verb",
"v-sapang-" : "verb",
"v-sapann-" : "verb",
"v-sapanv-" : "verb",
"v-sapema-" : "verb",
"v-sapemn-" : "verb",
"v-sapmfa-" : "verb",
"v-sapmfd-" : "verb",
"v-sapmfg-" : "verb",
"v-sapmfn-" : "verb",
"v-sapmma-" : "verb",
"v-sapmmd-" : "verb",
"v-sapmmg-" : "verb",
"v-sapmmn-" : "verb",
"v-sapmna-" : "verb",
"v-sapmng-" : "verb",
"v-sapmnn-" : "verb",
"v-sappfa-" : "verb",
"v-sappfd-" : "verb",
"v-sappfg-" : "verb",
"v-sappfn-" : "verb",
"v-sappma-" : "verb",
"v-sappmd-" : "verb",
"v-sappmg-" : "verb",
"v-sappmn-" : "verb",
"v-sappna-" : "verb",
"v-sappng-" : "verb",
"v-sappnn-" : "verb",
"v-sappnv-" : "verb",
"v-sfpafa-" : "verb",
"v-sfpafd-" : "verb",
"v-sfpafn-" : "verb",
"v-sfpama-" : "verb",
"v-sfpamd-" : "verb",
"v-sfpamg-" : "verb",
"v-sfpamn-" : "verb",
"v-sfpmfa-" : "verb",
"v-sfpmfd-" : "verb",
"v-sfpmfg-" : "verb",
"v-sfpmfn-" : "verb",
"v-sfpmma-" : "verb",
"v-sfpmmg-" : "verb",
"v-sfpmmn-" : "verb",
"v-sfpmna-" : "verb",
"v-sfppma-" : "verb",
"v-spiamn-" : "verb",
"v-spp-mn-" : "verb",
"v-spp-nn-" : "verb",
"v-sppa---" : "verb",
"v-sppafa-" : "verb",
"v-sppafd-" : "verb",
"v-sppafg-" : "verb",
"v-sppafn-" : "verb",
"v-sppafv-" : "verb",
"v-sppama-" : "verb",
"v-sppamd-" : "verb",
"v-sppamg-" : "verb",
"v-sppamn-" : "verb",
"v-sppamv-" : "verb",
"v-sppana-" : "verb",
"v-sppand-" : "verb",
"v-sppang-" : "verb",
"v-sppann-" : "verb",
"v-sppanv-" : "verb",
"v-sppefa-" : "verb",
"v-sppefd-" : "verb",
"v-sppefg-" : "verb",
"v-sppefn-" : "verb",
"v-sppema-" : "verb",
"v-sppemd-" : "verb",
"v-sppemg-" : "verb",
"v-sppemn-" : "verb",
"v-sppemv-" : "verb",
"v-sppena-" : "verb",
"v-sppend-" : "verb",
"v-sppeng-" : "verb",
"v-sppenn-" : "verb",
"v-spppfa-" : "verb",
"v-spppfd-" : "verb",
"v-spppfg-" : "verb",
"v-spppfn-" : "verb",
"v-spppma-" : "verb",
"v-spppmn-" : "verb",
"v-srp-mn-" : "verb",
"v-srpafa-" : "verb",
"v-srpafd-" : "verb",
"v-srpafg-" : "verb",
"v-srpafn-" : "verb",
"v-srpama-" : "verb",
"v-srpamd-" : "verb",
"v-srpamg-" : "verb",
"v-srpamn-" : "verb",
"v-srpamv-" : "verb",
"v-srpana-" : "verb",
"v-srpand-" : "verb",
"v-srpang-" : "verb",
"v-srpann-" : "verb",
"v-srpefa-" : "verb",
"v-srpefd-" : "verb",
"v-srpefg-" : "verb",
"v-srpefn-" : "verb",
"v-srpema-" : "verb",
"v-srpemd-" : "verb",
"v-srpemg-" : "verb",
"v-srpemn-" : "verb",
"v-srpemv-" : "verb",
"v-srpena-" : "verb",
"v-srpend-" : "verb",
"v-srpeng-" : "verb",
"v-srpenn-" : "verb",
"v-srppfn-" : "verb",
"v-srppma-" : "verb",
"v-srppmn-" : "verb",
"v-srppmv-" : "verb",
"v1paia---" : "verb",
"v1paim---" : "verb",
"v1paip---" : "verb",
"v1paoa---" : "verb",
"v1paom---" : "verb",
"v1paop---" : "verb",
"v1pasa---" : "verb",
"v1pase---" : "verb",
"v1pasm---" : "verb",
"v1pasp---" : "verb",
"v1pfia---" : "verb",
"v1pfim---" : "verb",
"v1pfom---" : "verb",
"v1piia---" : "verb",
"v1piie---" : "verb",
"v1plia---" : "verb",
"v1plie---" : "verb",
"v1ppia---" : "verb",
"v1ppie---" : "verb",
"v1ppip---" : "verb",
"v1ppoa---" : "verb",
"v1ppoe---" : "verb",
"v1ppsa---" : "verb",
"v1ppse---" : "verb",
"v1pria---" : "verb",
"v1prie---" : "verb",
"v1prsa---" : "verb",
"v1prse---" : "verb",
"v1ptie---" : "verb",
"v1s-sa---" : "verb",
"v1sa-a---" : "verb",
"v1saia---" : "verb",
"v1saie---" : "verb",
"v1saim---" : "verb",
"v1saip---" : "verb",
"v1sao----" : "verb",
"v1saoa---" : "verb",
"v1saoe---" : "verb",
"v1saom---" : "verb",
"v1saop---" : "verb",
"v1sasa---" : "verb",
"v1sase---" : "verb",
"v1sasm---" : "verb",
"v1sasp---" : "verb",
"v1sfi----" : "verb",
"v1sfia---" : "verb",
"v1sfie---" : "verb",
"v1sfim---" : "verb",
"v1sfip---" : "verb",
"v1siia---" : "verb",
"v1siie---" : "verb",
"v1slia---" : "verb",
"v1slie---" : "verb",
"v1slim---" : "verb",
"v1spia---" : "verb",
"v1spie---" : "verb",
"v1spoa---" : "verb",
"v1spoe---" : "verb",
"v1spsa---" : "verb",
"v1spse---" : "verb",
"v1sria---" : "verb",
"v1srie---" : "verb",
"v1sroa---" : "verb",
"v1sroe---" : "verb",
"v1srsa---" : "verb",
"v1stie---" : "verb",
"v1stim---" : "verb",
"v2daia---" : "verb",
"v2dama---" : "verb",
"v2dasa---" : "verb",
"v2dase---" : "verb",
"v2dfia---" : "verb",
"v2dfim---" : "verb",
"v2diia---" : "verb",
"v2diie---" : "verb",
"v2dpia---" : "verb",
"v2dpma---" : "verb",
"v2dpme---" : "verb",
"v2dria---" : "verb",
"v2drma---" : "verb",
"v2paia---" : "verb",
"v2paim---" : "verb",
"v2paip---" : "verb",
"v2pama---" : "verb",
"v2pame---" : "verb",
"v2pamm---" : "verb",
"v2paoa---" : "verb",
"v2paom---" : "verb",
"v2paop---" : "verb",
"v2pasa---" : "verb",
"v2pase---" : "verb",
"v2pasm---" : "verb",
"v2pasp---" : "verb",
"v2pfia---" : "verb",
"v2pfim---" : "verb",
"v2piia---" : "verb",
"v2piie---" : "verb",
"v2ppia---" : "verb",
"v2ppie---" : "verb",
"v2ppma---" : "verb",
"v2ppme---" : "verb",
"v2ppoa---" : "verb",
"v2ppoe---" : "verb",
"v2ppsa---" : "verb",
"v2pria---" : "verb",
"v2prie---" : "verb",
"v2prma---" : "verb",
"v2prmp---" : "verb",
"v2proa---" : "verb",
"v2prsa---" : "verb",
"v2saia---" : "verb",
"v2saie---" : "verb",
"v2saim---" : "verb",
"v2saip---" : "verb",
"v2sam----" : "verb",
"v2sama---" : "verb",
"v2same---" : "verb",
"v2samm---" : "verb",
"v2samp---" : "verb",
"v2saoa---" : "verb",
"v2saoe---" : "verb",
"v2saom---" : "verb",
"v2saop---" : "verb",
"v2sasa---" : "verb",
"v2sase---" : "verb",
"v2sasm---" : "verb",
"v2sasp---" : "verb",
"v2sfi----" : "verb",
"v2sfia---" : "verb",
"v2sfie---" : "verb",
"v2sfim---" : "verb",
"v2sfip---" : "verb",
"v2siia---" : "verb",
"v2siie---" : "verb",
"v2siip---" : "verb",
"v2slia---" : "verb",
"v2slie---" : "verb",
"v2slim---" : "verb",
"v2spia---" : "verb",
"v2spie---" : "verb",
"v2spma---" : "verb",
"v2spme---" : "verb",
"v2spoa---" : "verb",
"v2spoe---" : "verb",
"v2spsa---" : "verb",
"v2spse---" : "verb",
"v2sria---" : "verb",
"v2srie---" : "verb",
"v2srma---" : "verb",
"v2srme---" : "verb",
"v2sroa---" : "verb",
"v2srsa---" : "verb",
"v2stie---" : "verb",
"v3-roe---" : "verb",
"v3daia---" : "verb",
"v3daim---" : "verb",
"v3daip---" : "verb",
"v3daoa---" : "verb",
"v3dfia---" : "verb",
"v3dfim---" : "verb",
"v3diia---" : "verb",
"v3diie---" : "verb",
"v3dlia---" : "verb",
"v3dlie---" : "verb",
"v3dlim---" : "verb",
"v3dpia---" : "verb",
"v3dpie---" : "verb",
"v3dpma---" : "verb",
"v3dpme---" : "verb",
"v3dpsa---" : "verb",
"v3dria---" : "verb",
"v3pai----" : "verb",
"v3paia---" : "verb",
"v3paie---" : "verb",
"v3paim---" : "verb",
"v3paip---" : "verb",
"v3pamm---" : "verb",
"v3paoa---" : "verb",
"v3paoe---" : "verb",
"v3paom---" : "verb",
"v3paop---" : "verb",
"v3pasa---" : "verb",
"v3pase---" : "verb",
"v3pasm---" : "verb",
"v3pasp---" : "verb",
"v3pfia---" : "verb",
"v3pfie---" : "verb",
"v3pfim---" : "verb",
"v3piia---" : "verb",
"v3piie---" : "verb",
"v3piip---" : "verb",
"v3plia---" : "verb",
"v3plie---" : "verb",
"v3plim---" : "verb",
"v3plip---" : "verb",
"v3ppia---" : "verb",
"v3ppie---" : "verb",
"v3ppip---" : "verb",
"v3ppma---" : "verb",
"v3ppme---" : "verb",
"v3ppoa---" : "verb",
"v3ppoe---" : "verb",
"v3ppsa---" : "verb",
"v3ppse---" : "verb",
"v3pria---" : "verb",
"v3prie---" : "verb",
"v3prip---" : "verb",
"v3sai----" : "verb",
"v3saia---" : "verb",
"v3saie---" : "verb",
"v3saim---" : "verb",
"v3saip---" : "verb",
"v3sama---" : "verb",
"v3samm---" : "verb",
"v3samp---" : "verb",
"v3sana---" : "verb",
"v3sao----" : "verb",
"v3saoa---" : "verb",
"v3saoe---" : "verb",
"v3saom---" : "verb",
"v3saop---" : "verb",
"v3sas----" : "verb",
"v3sasa---" : "verb",
"v3sase---" : "verb",
"v3sasm---" : "verb",
"v3sasp---" : "verb",
"v3sfi----" : "verb",
"v3sfia---" : "verb",
"v3sfie---" : "verb",
"v3sfim---" : "verb",
"v3sfip---" : "verb",
"v3sfoa---" : "verb",
"v3sii----" : "verb",
"v3siia---" : "verb",
"v3siie---" : "verb",
"v3siip---" : "verb",
"v3sli----" : "verb",
"v3slia---" : "verb",
"v3slie---" : "verb",
"v3slim---" : "verb",
"v3slip---" : "verb",
"v3spia---" : "verb",
"v3spie---" : "verb",
"v3spip---" : "verb",
"v3spma---" : "verb",
"v3spme---" : "verb",
"v3spoa---" : "verb",
"v3spoe---" : "verb",
"v3spop---" : "verb",
"v3spsa---" : "verb",
"v3spse---" : "verb",
"v3sria---" : "verb",
"v3srie---" : "verb",
"v3srip---" : "verb",
"v3srma---" : "verb",
"v3sroa---" : "verb",
"v3srsa---" : "verb",
"v3stie---" : "verb",
"v3stim---" : "verb",
"v3stip---" : "verb",
"x--------" : "x",
"x-p----d-" : "x",
"x-p---nn-" : "x",
}


def buildictmorpheus(context):
    corpus = dict() # creates the dictionary for the corpus
    filenames = dict() # creates a dictionary for the filenames and their content

    i = 0

    for event, elem in context:
    
        univpos = univ_pos_name_variants[elem[5].text]  # <morphological-analysis>a-s---fa-</morphological-analysis>
        form = elem[1].text                             # <word-form>ἀάατον</word-form>
        lemma = elem[3].text                            # <lemma>ἀάατος</lemma>
        
        if "lemma_lookup_"+univpos in list(filenames.keys()):
            these_lemmas = filenames["lemma_lookup_"+univpos]
        else: 
            these_lemmas = dict()
            filenames.update({"lemma_lookup_"+univpos : these_lemmas})
           
        thelemma = lemma 
       
        if form in corpus and univpos in list(corpus[form].keys()) and not lemma == corpus[form][univpos]:
            print(i, "Alert of collision! word: ", form, " pos: ", univpos, " lemma1: ", corpus[form][univpos], " lemma2: ", lemma)
            thelemma = whichone(form, univpos, corpus[form][univpos], lemma)   
            
        if thelemma:  # if thelemma is not None
            corpus.update({ form : { univpos: thelemma }  }) 
            these_lemmas.update({ form : thelemma })           
           
        print(i)
        i+=1
        
        # It's safe to call clear() here because no descendants will be accessed
        elem.clear(keep_tail=True)
 
        # Also eliminate now-empty references from the root node to <Title> 
        while elem.getprevious() is not None:
            del elem.getparent()[0]

    for name, content in filenames.items():
       print("created filename: ", name)
    
    return filenames
    
def whichone(form, univpos, lemma1, lemma2):
    # api-endpoint 
    # http://services.perseids.org/bsp/morphologyservice/analysis/word?lang=grc&engine=morpheusgrc&word=%E1%BC%80%CF%80%CE%BF%CE%BA%CE%B1%CE%BB%CF%8D%CF%88%CE%B5%CE%B9
    URL = "http://services.perseids.org/bsp/morphologyservice/analysis/word"
   
    # location given here 
    location = "delhi technological university"
  
    # defining a params dict for the parameters to be sent to the API 
    PARAMS = {'lang':'grc', 'engine':'morpheusgrc', 'word':form} 
  
    # sending get request and saving the response as response object 
    r = requests.get(URL, PARAMS) 
  
    # extracting data in json format 
    data = r.json() 
    #print("data:", data)
    print("======================================================================== perseids")
    print(json.dumps(data, indent=4, ensure_ascii=False))
    encoding = 'utf-8'
    
    if "Body" in data["RDF"]["Annotation"]: # if the answer is not empty 
        hasBody = data["RDF"]["Annotation"]["Body"]
    
        if isinstance(hasBody, list): # it gets the first group of answers if many groups
            answer = data["RDF"]["Annotation"]["Body"][0]["rest"]["entry"]["dict"]["hdwd"]["$"]
        else: 
            answer = data["RDF"]["Annotation"]["Body"]["rest"]["entry"]["dict"]["hdwd"]["$"]   
    
        #if isinstance(answer, list) : # it gets the first answer if many
        #    word = answer[0]["term"]["stem"]["$"]
        #else: 
        #    word = answer["term"]["stem"]["$"] 
        
        word = answer
            
    else:
        word = None # it chooses none. this word will be dismissed
        
    lemma = word # chr(int(word, 16))
    
    if word==lemma1: 
        print("first lemma was right", lemma1)
    elif word==lemma2:
        print("second lemma was right", lemma2)
    elif word==None:
        print("The word ", form, " will be dismissed")
    else:
        print("None was right. ", word, " will be used anew")
    
    return lemma


def buildindexmorpheus(context):
    index = dict()
    
    for event, elem in context:
        pos = elem[5].text                              # <morphological-analysis>a-s---fa-</morphological-analysis>
        form = elem[1].text                             # <word-form>ἀάατον</word-form>
        lemma = elem[3].text                            # <lemma>ἀάατος</lemma>
        
        univpos = univ_pos_name_variants[pos]
        lemmas = [lemma]
        if univpos in index:
            first_lemmas = index[univpos]
            if lemma not in first_lemmas: 
                index.update({ univpos : first_lemmas+lemmas })
        else:
            index.update({ univpos : lemmas })    
       
        # It's safe to call clear() here because no descendants will be accessed
        elem.clear(keep_tail=True)                            
                
    return index

def buildposmorpheus(context):
    index = dict()
    
    for event, elem in context:
        pos = elem[5].text                              # <morphological-analysis>a-s---fa-</morphological-analysis>
        form = elem[1].text                             # <word-form>ἀάατον</word-form>
        lemma = elem[3].text                            # <lemma>ἀάατος</lemma>
        
        if pos in univ_pos_name_variants or pos in index:
            pass
        else:
            index.update({ pos : "x" })
            print('\"', pos, "\" : \"x\"")    
       
        # It's safe to call clear() here because no descendants will be accessed
        elem.clear(keep_tail=True)                            
                
    return index
 
    
def reportposmorpheus(context):
    #index = dict()
    
    with open('report.tsv', 'w', newline='') as r:
        writer = csv.writer(r,  delimiter='\t',
                            quotechar='"', quoting=csv.QUOTE_ALL)
        writer.writerow(['token','pos','lemma'])  # WRITING HEADERS
    
        for event, elem in context:
            pos = elem[5].text                              # <morphological-analysis>a-s---fa-</morphological-analysis>
            form = elem[1].text                             # <word-form>ἀάατον</word-form>
            lemma = elem[3].text                            # <lemma>ἀάατος</lemma>
        
            if pos.startswith('t') or pos.startswith('-') or pos.startswith('_'):
                writer.writerow([form, pos, lemma])
            else:
                pass    
       
            # It's safe to call clear() here because no descendants will be accessed
            elem.clear(keep_tail=True)                            
                
    return {} 

def createfiles(filenamesdict):

    for name, content in filenamesdict.items():

        with open(name+'.json', 'w', encoding='utf-8') as f:
            corpus = collections.OrderedDict(sorted(content.items())) 
            json.dump(corpus, f, ensure_ascii=False, indent=4)    
  

def main(argv):
    splitted = False
    infile = ''
    outfile = ''
    #func = buildposmorpheus
    #print(argv)
    try:
        opts, args = getopt.gnu_getopt(argv,"rhpnci:o:",["report", "pos", "index", "corpus","ifile=","ofile="])
        #print(opts, args)
    except getopt.GetoptError:
        print('readingbigcorpus.py --<pos|index|corpus> -i <inputfile> -o <outputfile>')
        sys.exit(2)
    for opt, arg in opts:
        if opt == '-h':
            print('readingbigcorpus.py --<pos|index|corpus> -i <inputfile> -o <outputfile>')
            sys.exit()
        elif opt in ("-r", "--report"):
            func = reportposmorpheus
            print("Reporting token, pos, lemma in a tsv. Not json")
        elif opt in ("-p", "--pos"):
            func = buildposmorpheus
            print("Building the pos file")
        elif opt in ("-n", "--index"):
            func = buildindexmorpheus
            print("Building the index")
        elif opt in ("-c", "--corpus"):
            func = buildictmorpheus 
            splitted = True
            print("Building lemma_lookup")    
        elif opt in ("-i", "--ifile"):
            infile = arg
            print("from file", infile)  
        elif opt in ("-o", "--ofile"):
            outfile = arg
            print("on file", outfile)  
    
    
    #print(func, infile, outfile)
         
    context = etree.iterparse(infile, events=('end',), tag='t')

    print('\nStart of corpus generation:')
     
    data = func(context)
    
    if splitted: 
    
        createfiles(data)
        
    else: 

        print("Data size:", len(data))

        with open(outfile, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=4)

    print('\nEnd of corpus generation:')


if __name__ == "__main__":
   main(sys.argv[1:])


